{
  "hash": "0ff182fcdb671b8666e66b6d6fc3c027",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuições de frequências e representações gráficas\n\nDepois de compreender a estrutura de um banco de dados e verificar sua qualidade, uma das primeiras tarefas da Análise Exploratória de Dados é **descrever como os valores de uma variável se distribuem**.\n\nDuas ferramentas aparecem naturalmente nesse processo:\n\n- as **tabelas de frequências**, que organizam contagens, proporções e percentuais de forma precisa;\n- as **representações gráficas**, que tornam mais visíveis concentração, predominância, dispersão, forma e possíveis características incomuns dos dados.\n\nEssas ferramentas não devem ser estudadas como assuntos independentes. Em geral, a tabela organiza numericamente a distribuição e o gráfico oferece uma leitura visual da mesma informação. Ao longo deste capítulo, sempre que possível, a construção conceitual será seguida de sua interpretação e de um **Laboratório no R**.\n\n::: {.callout-tip title=\"Objetivos do capítulo\"}\nAo final deste capítulo, espera-se que você seja capaz de:\n\n- construir e interpretar distribuições de frequências para variáveis qualitativas e quantitativas;\n- distinguir frequência absoluta, relativa, percentual e acumulada;\n- reconhecer quando uma frequência acumulada possui significado;\n- organizar variáveis quantitativas contínuas em classes;\n- calcular amplitude total, limites, amplitude e ponto médio das classes;\n- utilizar e interpretar as regras da raiz quadrada, de Sturges, de Scott e de Freedman--Diaconis;\n- relacionar tabelas de frequências às representações gráficas correspondentes;\n- distinguir gráfico de barras, Pareto, setores, pontos, histograma, polígono de frequências, ogiva, ramo e folhas e curva de densidade;\n- reproduzir tabelas e gráficos no R de forma coerente com os conceitos estudados;\n- interpretar resultados estatísticos sem se limitar a descrever números ou comandos.\n:::\n\n## Variáveis qualitativas e quantitativas discretas\n\nQuando uma variável possui um conjunto relativamente pequeno de categorias ou valores distintos, podemos apresentar diretamente cada categoria ou valor observado e sua frequência. Isso ocorre naturalmente com variáveis **qualitativas** e com muitas variáveis **quantitativas discretas**.\n\n### Conceitos fundamentais de frequência e tabelas\n\n#### Dos dados individuais para uma distribuição\n\nConsidere o número de faltas de 20 estudantes em determinada disciplina:\n\n$$0,\\ 2,\\ 1,\\ 3,\\ 2,\\ 0,\\ 4,\\ 1,\\ 2,\\ 2,\\ 5,\\ 0,\\ 1,\\ 3,\\ 2,\\ 4,\\ 1,\\ 2,\\ 0,\\ 3.$$\n\nEsses são os **dados brutos**. Eles preservam todas as observações individualmente, mas a leitura direta não é a forma mais eficiente de responder a perguntas como:\n\n- qual número de faltas ocorreu com maior frequência?\n- quantos estudantes não tiveram faltas?\n- qual proporção apresentou exatamente duas faltas?\n- quantos tiveram no máximo duas faltas?\n- quantos tiveram pelo menos três faltas?\n\nUma primeira organização consiste em construir o **rol**, isto é, ordenar os valores:\n\n$$0,\\ 0,\\ 0,\\ 0,$$\n\n$$ 1,\\ 1,\\ 1,\\ 1, $$\n\n$$2,\\ 2,\\ 2,\\ 2,\\ 2,\\ 2, $$\n\n$$3,\\ 3,\\ 3,$$\n\n$$4,\\ 4,$$\n\n$$5.$$\n\nO rol facilita a percepção das repetições, mas ainda exige que contemplemos cada observação. A **distribuição de frequências** dá um passo além: reúne valores iguais e informa quantas vezes cada um ocorre.\n\n| Número de faltas ($x_i$) | Número de estudantes ($f_i$) |\n|-------------------------:|-----------------------------:|\n|                        0 |                            4 |\n|                        1 |                            4 |\n|                        2 |                            6 |\n|                        3 |                            3 |\n|                        4 |                            2 |\n|                        5 |                            1 |\n|                **Total** |                       **20** |\n\n: Distribuição de frequências do número de faltas de 20 estudantes. {#tbl-faltas}\n\nA @tbl-faltas mostra que **duas faltas** foi o valor mais frequente, observado em 6 dos 20 estudantes. Também se verifica que 4 estudantes não tiveram faltas e que os números mais elevados de faltas ocorreram com menor frequência. A tabela permite, portanto, identificar rapidamente a concentração das observações nos menores valores da variável.\n\nVinte observações individuais foram resumidas em seis linhas. A tabela não preserva a identidade nem a ordem original dos estudantes, mas conserva a informação necessária para compreender a distribuição da variável.\n\n::: {.callout-note title=\"Resumir implica escolher o que preservar\"}\nUma tabela de frequências preserva os valores observados e suas contagens, mas não preserva a posição original de cada unidade no banco. Isso não é um defeito: é justamente o propósito do resumo estatístico. O importante é compreender qual informação foi condensada.\n:::\n\nUsaremos a seguinte notação:\n\n- $n$: número total de observações;\n- $k$: número de categorias ou valores distintos apresentados na tabela;\n- $x_i$: categoria ou valor correspondente à linha $i$;\n- $f_i$: frequência absoluta da categoria ou valor $i$.\n\nNo exemplo,\n\n$$n=20, \\qquad k=6.$$\n\nPara $x_i=2$,\n\n$$f_i=6.$$\n\nLogo, seis estudantes apresentaram exatamente duas faltas. A soma das frequências absolutas deve reproduzir o total de observações:\n\n$$\\sum_{i=1}^{k}f_i=n.$$\n\nNeste caso,\n\n$$4+4+6+3+2+1=20.$$\n\nEssa é uma verificação básica de consistência da tabela.\n\n#### Frequência absoluta, relativa, percentual e acumulada\n\nA **frequência absoluta**, representada por $f_i$, informa quantas observações pertencem a uma categoria ou assumem determinado valor.\n\nPara duas faltas:\n\n$$f(2)=6.$$\n\nA frequência absoluta responde à pergunta:\n\n> **quantas observações?**\n\nEntretanto, a contagem isolada depende do tamanho do conjunto. Se uma turma possui 20 estudantes e outra possui 100, uma frequência igual a 10 representa situações bastante diferentes. Para comparar, usamos a **frequência relativa** $(f_{r_i})$ que expressa a frequência como uma proporção do total:\n\n$$f_{r_i}=\\frac{f_i}{n}.$$\n\nPara duas faltas:\n\n$$f_r(2)=\\frac{6}{20}=0{,}30.$$\n\nPortanto, a frequência relativa é 0,30.\n\nA **frequência percentual** $(f_{r_i}\\%)$ apresenta a mesma informação em porcentagem:\n\n$$f_{r_i}{\\%}=100\\times f_{r_i}.$$\n\nAssim,\n\n$$f_{r_i}(2){\\%}=30\\%.$$\n\nPodemos então dizer:\n\n> 6 estudantes tiveram exatamente 2 faltas, correspondendo a 30% dos 20 estudantes observados.\n\nA tabela passa a ser:\n\n|     $x_i$ |  $f_i$ | $f_{r_i}$ | $f_{\\%i}$ |\n|----------:|-------:|----------:|----------:|\n|         0 |      4 |      0,20 |       20% |\n|         1 |      4 |      0,20 |       20% |\n|         2 |      6 |      0,30 |       30% |\n|         3 |      3 |      0,15 |       15% |\n|         4 |      2 |      0,10 |       10% |\n|         5 |      1 |      0,05 |        5% |\n| **Total** | **20** |  **1,00** |  **100%** |\n\nDuas verificações são esperadas:\n\n$$\\sum_{i=1}^{K}f_{r_i}=1$$\n\ne\n\n$$\\sum_{i=1}^{K}f_{r_i}{\\%}=100\\%.$$\n\nEm tabelas publicadas, a soma dos percentuais pode resultar em `99,9%` ou `100,1%` devido ao arredondamento. Isso não significa necessariamente que a tabela esteja errada.\n\nQuando as categorias ou valores possuem uma **ordem com significado**, podemos calcular frequências acumuladas.\n\nA **frequência absoluta acumulada** $(F_i)$ é\n\n$$F_i=\\sum_{j=1}^{i}f_j.$$\n\nPara a variável `faltas`:\n\n$$F(0)=4.$$ $$F(1)=4+4=8.$$ $$F(2)=4+4+6=14.$$\n\nA tabela completa é:\n\n|     $x_i$ |  $f_i$ | $f_{r_i}$ | $f_{\\%i}$ | $F_i$ | $F_{r_i}$ | $F_{\\%i}$ |\n|----------:|-------:|----------:|----------:|------:|----------:|----------:|\n|         0 |      4 |      0,20 |       20% |     4 |      0,20 |       20% |\n|         1 |      4 |      0,20 |       20% |     8 |      0,40 |       40% |\n|         2 |      6 |      0,30 |       30% |    14 |      0,70 |       70% |\n|         3 |      3 |      0,15 |       15% |    17 |      0,85 |       85% |\n|         4 |      2 |      0,10 |       10% |    19 |      0,95 |       95% |\n|         5 |      1 |      0,05 |        5% |    20 |      1,00 |      100% |\n| **Total** | **20** |  **1,00** |  **100%** | **-** |     **-** |     **-** |\n\nAgora podemos interpretar: $$F(2) = 14$$\n\nIsso significa:\n\n> 14 dos 20 estudantes tiveram **no máximo duas faltas**.\n\nA **frequência relativa acumulada (**$F_{r_i}$) correspondente é: $$F_r(2) = 0,70$$\n\nPortanto:\n\n> 70% dos estudantes tiveram no máximo duas faltas.\n\nObserve que uma frequência acumulada não responde a “quantos tiveram exatamente 2”, mas a “quantos tiveram **até 2**”.\n\n::: {.callout-important title=\"Exatamente, no máximo e pelo menos\"}\n**Exatamente 2** → utilize $f(2)$.\n\n**No máximo 2** → inclua $0,1,2$; utilize a frequência acumulada $F(2)$.\n\n**Pelo menos 2** → inclua $2,3,4,5,\\ldots$; some as frequências a partir de 2 ou subtraia do total as frequências abaixo de 2.\n:::\n\nPor exemplo,\n\n$$\\text{pelo menos 3 faltas}=3+2+1=6,$$\n\nportanto,\n\n$$\\frac{6}{20}=0{,}30=30\\%.$$\n\n### Variável qualitativa nominal\n\nUma distribuição de frequências também pode ser construída para variáveis qualitativas. Considere o meio de transporte utilizado por 80 estudantes para chegar à universidade:\n\n| Meio de transporte |  $f_i$ | $f_{r_i}$ | Percentual |\n|:-------------------|-------:|----------:|-----------:|\n| Ônibus             |     30 |    0,3750 |      37,5% |\n| Carro              |     15 |    0,1880 |      18,8% |\n| Aplicativo/táxi    |     14 |    0,1750 |      17,5% |\n| Motocicleta        |      9 |    0,1120 |      11,2% |\n| A pé               |      7 |    0,0875 |      8,75% |\n| Bicicleta          |      5 |    0,0625 |      6,25% |\n| **Total**          | **80** | **1,000** | **100,0%** |\n\n: Distribuição de frequências do meio de transporte utilizado por 80 estudantes. {#tbl-meio-transporte}\n\nA @tbl-meio-transporte evidencia uma concentração importante nas três categorias mais frequentes: **ônibus, carro e aplicativo/táxi**, que juntas reúnem 73,75% dos estudantes. Isso mostra que quase três quartos do grupo utilizam um desses três meios para chegar à universidade.\n\nA variável `meio de transporte` é **qualitativa nominal**: suas categorias não possuem ordem natural. Podemos interpretar:\n\n> O ônibus foi o meio de transporte mais frequente, utilizado por 30 dos 80 estudantes, ou 37,5% do grupo.\n\nNão faz sentido calcular uma frequência acumulada na ordem `Ônibus`, `Carro`, `Motocicleta`, etc., porque a ordem das categorias é apenas uma decisão de apresentação.\n\nPara categorias nominais, podemos organizar a tabela em ordem:\n\n- alfabética;\n- definida pelo instrumento de coleta;\n- de interesse substantivo;\n- decrescente de frequência.\n\nOrdenar as categorias pela frequência não transforma a variável em ordinal.\n\n#### Gráfico de barras\n\nO **gráfico de barras** é uma das representações mais úteis para variáveis qualitativas. Cada barra representa uma categoria, e sua altura representa uma frequência absoluta, relativa ou percentual.\n\nAs barras são separadas porque representam categorias distintas. Para variáveis nominais, a ordem pode ser escolhida de acordo com o objetivo da apresentação.\n\nA tabela anterior pode ser visualizada esquematicamente como:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nA @fig-barras-meio-transporte evidencia o predomínio do ônibus como meio de transporte mais utilizado pelos estudantes. Também chama atenção a proximidade entre as frequências de carro e aplicativo, enquanto bicicleta aparece como a alternativa menos frequente.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribuição dos estudantes segundo o meio de transporte utilizado.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-barras-meio-transporte-1.png){#fig-barras-meio-transporte width=672}\n:::\n:::\n\n\n\n\nO gráfico facilita a percepção imediata da categoria predominante; a tabela, por sua vez, preserva as contagens e percentuais exatos.\n\nNo gráfico de barras:\n\n- as categorias aparecem em um eixo;\n- as frequências aparecem no outro;\n- as barras são separadas, pois cada uma representa uma categoria distinta.\n\n#### Gráfico de Pareto\n\nO **gráfico de Pareto** é um gráfico de barras no qual as categorias aparecem em ordem decrescente de frequência. Costuma-se acrescentar uma linha representando o percentual acumulado.\n\nPara o exemplo:\n\n| Meio de transporte |  $f_i$ | $F_{r_i}$ | Percentual acumulado |\n|:-------------------|-------:|----------:|---------------------:|\n| Ônibus             |     30 |    0,3750 |               37,50% |\n| Carro              |     15 |    0,5630 |               56,30% |\n| Aplicativo/táxi    |     14 |    0,7380 |               73,80% |\n| Motocicleta        |      9 |    0,8500 |               85,00% |\n| A pé               |      7 |    0,9375 |               93,75% |\n| Bicicleta          |      5 |    1,0000 |                1,00% |\n| **Total**          | **80** |     **-** |                **-** |\n\nObserve que a acumulação do Pareto segue a **ordem decrescente de frequência**, e não uma ordem natural da variável. Portanto, sua interpretação é diferente da frequência acumulada de uma variável ordinal ou quantitativa.\n\n\n\n\n\n\n\n\n\nA @fig-pareto-meio-transporte mostra que o **ônibus** é o meio de transporte mais frequente, utilizado por 30 dos 80 estudantes, correspondendo a **37,5%** do total. Quando acrescentamos os estudantes que utilizam **carro**, o percentual acumulado atinge **56,25%**; com a inclusão de **aplicativo**, chega a **73,75%**.\n\nA linha de percentual acumulado mostra ainda que as quatro categorias mais frequentes — ônibus, carro, aplicativo e motocicleta — reúnem **85% dos estudantes**, ultrapassando a referência de 80% indicada pela linha tracejada. Assim, embora existam seis meios de transporte registrados, a maior parte dos estudantes concentra-se nessas quatro categorias.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Gráfico de Pareto do meio de transporte utilizado pelos 80 estudantes.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-pareto-meio-transporte-1.png){#fig-pareto-meio-transporte width=672}\n:::\n:::\n\n\n\n\n#### Gráfico de setores\n\nO **gráfico de setores** representa cada categoria como uma parcela de um círculo de $360^\\circ$. O tamanho de cada setor é proporcional à frequência relativa da categoria.\n\nEle pode ser útil quando há poucas categorias e o objetivo é enfatizar a composição de um total. Entretanto, a comparação visual entre ângulos e áreas costuma ser menos precisa do que a comparação entre comprimentos de barras. Por isso, para muitas categorias ou quando a comparação exata é importante, o gráfico de barras geralmente é mais eficiente.\n\nPara construir o gráfico manualmente, precisamos transformar a frequência de cada categoria em um **ângulo central**.\n\nSe uma categoria possui frequência absoluta $f_i$ em um conjunto com $n$ observações, sua frequência relativa é\n\n$$f_{r_i}=\\frac{f_i}{n}.$$\n\nComo o círculo completo possui $360^\\circ$, o ângulo correspondente à categoria é\n\n$$\\theta_i\n=\nf_{r_i}\\times360^\\circ.$$\n\nPortanto,\n\n$$\\theta_i\n=\n\\frac{f_i}{n}\\times360^\\circ.$$\n\nSe a informação estiver apresentada em percentual, podemos utilizar\n\n$$\\theta_i\n=\n\\frac{p_i}{100}\\times360^\\circ,$$\n\nou, de maneira equivalente,\n\n$$\\theta_i=3{,}6\\,p_i,$$\n\nem que $p_i$ representa o percentual da categoria.\n\nPara o exemplo:\n\n| Meio de transporte |  $f_i$ |  $f_{r_i}$ |  Percentual |         Ângulo |\n|:-------------------|-------:|-----------:|------------:|---------------:|\n| Ônibus             |     30 |     0,3750 |      37,50% |    $135^\\circ$ |\n| Carro              |     15 |     0,1875 |      18,75% | $67{,}5^\\circ$ |\n| Aplicativo         |     14 |     0,1750 |      17,50% |     $63^\\circ$ |\n| Motocicleta        |      9 |     0,1125 |      11,25% | $40{,}5^\\circ$ |\n| A pé               |      7 |     0,0875 |       8,75% | $31{,}5^\\circ$ |\n| Bicicleta          |      5 |     0,0625 |       6,25% | $22{,}5^\\circ$ |\n| **Total**          | **80** | **1,0000** | **100,00%** |    $360^\\circ$ |\n\nPor exemplo, para a categoria **Ônibus**:\n\n$$\\theta_{\\text{Ônibus}}\n=\n\\frac{30}{80}\\times360^\\circ\n=\n135^\\circ.$$\n\nPara **Carro**:\n\n$$\\theta_{\\text{Carro}}\n=\n\\frac{15}{80}\\times360^\\circ\n=\n67{,}5^\\circ.$$\n\nE, para **Aplicativo**:\n\n$$\\theta_{\\text{Aplicativo}}\n=\n\\frac{14}{80}\\times360^\\circ\n=\n63^\\circ.$$\n\nOs demais setores são obtidos da mesma maneira.\n\n::: {.callout-tip title=\"Como esboçar o gráfico de setores\"}\n1.  Desenhe um círculo e marque o seu centro.\n2.  Trace um raio para servir como ponto inicial.\n3.  Com um transferidor, marque sucessivamente os ângulos:\n\n$$135^\\circ,\\quad\n67{,}5^\\circ,\\quad\n63^\\circ,\\quad\n40{,}5^\\circ,\\quad\n31{,}5^\\circ,\\quad\n22{,}5^\\circ.$$\n\n4.  Identifique cada setor com sua categoria.\n5.  Se desejar, acrescente também os percentuais correspondentes.\n\nAo final, os setores devem completar todo o círculo.\n\n$$135\n+\n67{,}5\n+\n63\n+\n40{,}5\n+\n31{,}5\n+\n22{,}5\n=\n360^\\circ.$$\n:::\n\n::: {.callout-note title=\"Uma relação útil\"}\nComo há 80 estudantes,\n\n$$\\frac{360^\\circ}{80}=4{,}5^\\circ.$$\n\nAssim, **cada estudante representa** $4{,}5^\\circ$ do círculo.\n\nPor exemplo, 30 estudantes correspondem a\n\n$$30\\times4{,}5^\\circ=135^\\circ.$$\n\nEssa relação torna a construção manual particularmente simples neste exemplo.\n:::\n\nA @fig-setores-meio-transporte evidencia a predominância do **ônibus**, utilizado por 37,5% dos estudantes. Somados, ônibus, carro e aplicativo representam **73,75% dos 80 estudantes**, enquanto bicicleta corresponde à menor parcela, com 6,25%.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Gráfico de setores do meio de transporte utilizado pelos 80 estudantes.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-setores-meio-transporte-1.png){#fig-setores-meio-transporte width=672}\n:::\n:::\n\n\n\n\n::: {.callout-tip title=\"Tabela e gráfico cumprem funções complementares\"}\nA tabela permite localizar frequências com precisão. O gráfico permite perceber rapidamente diferenças de magnitude e padrões gerais. Uma boa análise pode utilizar ambos, evitando repetir informação sem necessidade.\n:::\n\n::: {.callout-tip title=\"Da teoria à prática\"}\nA tabela e os gráficos acima foram construídos para compreender a lógica estatística. No **Laboratório no R**, reproduziremos as mesmas ideias computacionalmente. O objetivo do código é automatizar procedimentos já compreendidos, não substituir sua interpretação.\n:::\n\n#### Laboratório no R\n\nNesta prática utilizaremos um único banco para acompanhar diferentes tipos de variáveis ao longo do capítulo. O arquivo contém 80 estudantes e inclui variáveis qualitativas, quantitativas discretas e quantitativas contínuas.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_csv(\n  \"dados/estudantes80n.csv\",\n  show_col_types = FALSE\n)\n\nglimpse(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 80\nColumns: 8\n$ id_estudante           <chr> \"E001\", \"E002\", \"E003\", \"E004\", \"E005\", \"E006\",…\n$ curso                  <chr> \"Química\", \"Física\", \"Física\", \"Física\", \"Físic…\n$ meio_transporte        <chr> \"Ônibus\", \"Aplicativo\", \"Carro\", \"Aplicativo\", …\n$ satisfacao             <chr> \"Alta\", \"Muito alta\", \"Alta\", \"Alta\", \"Alta\", \"…\n$ idade_anos             <dbl> 25, 21, 26, 23, 19, 19, 22, 23, 21, 17, 17, 19,…\n$ faltas                 <dbl> 1, 1, 2, 2, 5, 4, 2, 3, 4, 1, 2, 5, 3, 1, 1, 3,…\n$ tempo_deslocamento_min <dbl> 96.5, 37.7, 45.1, 51.0, 112.0, 14.0, 35.7, 27.9…\n$ altura_m               <dbl> 1.75, 1.71, 1.63, 1.59, 1.61, 1.64, 1.65, 1.69,…\n```\n\n\n:::\n:::\n\n\n\n\nAntes de resumir qualquer variável, verifique seus valores e possíveis ausências:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summarise(\n    n = n(),\n    ausentes_curso = sum(is.na(curso)),\n    ausentes_transporte = sum(is.na(meio_transporte)),\n    ausentes_satisfacao = sum(is.na(satisfacao)),\n    ausentes_faltas = sum(is.na(faltas))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n      n ausentes_curso ausentes_transporte ausentes_satisfacao ausentes_faltas\n  <int>          <int>               <int>               <int>           <int>\n1    80              0                   0                   0               0\n```\n\n\n:::\n:::\n\n\n\n\nComecemos por `meio_transporte`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte <- dados |>\n  count(meio_transporte, name = \"fi\") |>\n  mutate(\n    fr = fi / sum(fi),\n    percentual = 100 * fr\n  )\n\ntab_transporte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  meio_transporte    fi     fr percentual\n  <chr>           <int>  <dbl>      <dbl>\n1 A pé                7 0.0875       8.75\n2 Aplicativo         14 0.175       17.5 \n3 Bicicleta           5 0.0625       6.25\n4 Carro              15 0.188       18.8 \n5 Motocicleta         9 0.112       11.2 \n6 Ônibus             30 0.375       37.5 \n```\n\n\n:::\n:::\n\n\n\n\nUma tabela pronta para apresentação pode ser produzida por:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte |>\n  mutate(\n    fr = round(fr, 3),\n    percentual = round(percentual, 1)\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"Meio de transporte\",\n      \"fi\",\n      \"fr\",\n      \"Percentual (%)\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Meio de transporte | fi|    fr| Percentual (%)|\n|:------------------|--:|-----:|--------------:|\n|A pé               |  7| 0.088|            8.8|\n|Aplicativo         | 14| 0.175|           17.5|\n|Bicicleta          |  5| 0.062|            6.2|\n|Carro              | 15| 0.188|           18.8|\n|Motocicleta        |  9| 0.112|           11.2|\n|Ônibus             | 30| 0.375|           37.5|\n\n\n:::\n:::\n\n\n\n\nO **gráfico de barras** usa exatamente as frequências que acabamos de calcular:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte |>\n  ggplot(\n    aes(\n      x = reorder(meio_transporte, fi),\n      y = fi\n    )\n  ) +\n  geom_col() +\n  coord_flip() +\n  labs(\n    title = \"Meio de transporte dos estudantes\",\n    x = NULL,\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nPara alterar a cor das barras, use o argumento `fill` dentro de `geom_col()`:\n\n- `fill` altera o preenchimento das barras.\n\n- `color` altera apenas a borda:\n\n``` r\ngeom_col(fill = \"#2A9D8F\", color = \"#1D3557\")\n```\n\nPara dar uma cor diferente a cada meio de transporte, coloque `fill` dentro de `aes()`:\n\n``` r\ngeom_col(aes(fill = meio_transporte)) + guides(fill = \"none\")\n```\n\ne\n\n``` r\nguides(fill = \"none\")  \n```\n\nremove a legenda das cores. Se quiser mantê-la, basta retirar essa linha ou deixar explícito que ela deve aparecer assim, por exemplo, `guides(fill = guide_legend(title = \"Transporte\"))`. Assim, cada barra terá uma cor e a legenda aparecerá com o título Transporte.\n\n**Barras com percentuais**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte |>\n  mutate(\n    fr = round(fr, 3),\n    percentual = round(percentual, 1)\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"Meio de transporte\",\n      \"fi\",\n      \"fr\",\n      \"Percentual (%)\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Meio de transporte | fi|    fr| Percentual (%)|\n|:------------------|--:|-----:|--------------:|\n|A pé               |  7| 0.088|            8.8|\n|Aplicativo         | 14| 0.175|           17.5|\n|Bicicleta          |  5| 0.062|            6.2|\n|Carro              | 15| 0.188|           18.8|\n|Motocicleta        |  9| 0.112|           11.2|\n|Ônibus             | 30| 0.375|           37.5|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte |>\n  ggplot(\n    aes(\n      x = reorder(meio_transporte, percentual),\n      y = percentual\n    )\n  ) +\n  geom_col() +\n  coord_flip() +\n  labs(\n    title = \"Distribuição percentual do meio de transporte\",\n    x = \"Meio de transporte\",\n    y = \"Percentual (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.callout-note title=\"Frequência ou percentual?\"}\nSe todos os gráficos se referem ao mesmo conjunto de 80 estudantes, frequência e percentual transmitem a mesma ordenação.\n\nPercentuais tornam-se especialmente úteis quando desejamos comunicar composição ou comparar grupos de tamanhos diferentes.\n:::\n\nPara construir um **Pareto**, ordenamos as categorias da maior para a menor frequência e calculamos o percentual acumulado nessa ordem:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_pareto <- tab_transporte |>\n  arrange(desc(fi)) |>\n  mutate(\n    percentual_acumulado = cumsum(percentual),\n    meio_transporte = factor(\n      meio_transporte,\n      levels = meio_transporte\n    )\n  )\n\ntab_pareto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  meio_transporte    fi     fr percentual percentual_acumulado\n  <fct>           <int>  <dbl>      <dbl>                <dbl>\n1 Ônibus             30 0.375       37.5                  37.5\n2 Carro              15 0.188       18.8                  56.2\n3 Aplicativo         14 0.175       17.5                  73.8\n4 Motocicleta         9 0.112       11.2                  85  \n5 A pé                7 0.0875       8.75                 93.8\n6 Bicicleta           5 0.0625       6.25                100  \n```\n\n\n:::\n:::\n\n\n\n\nComo frequência absoluta e percentual estão em escalas diferentes, precisamos fazer uma transformação para que ambos possam aparecer no mesmo gráfico.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfator_escala <- max(tab_pareto$fi) / 100\n```\n:::\n\n\n\n\nO gráfico de barras correspondente é:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_pareto |>\n  ggplot(\n    aes(x = meio_transporte)\n  ) +\n  geom_col(\n    aes(y = fi)\n  ) +\n  geom_line(\n    aes(\n      y = percentual_acumulado * fator_escala,\n      group = 1\n    ),\n    linewidth = 1\n  ) +\n  geom_point(\n    aes(\n      y = percentual_acumulado * fator_escala\n    ),\n    size = 2.5\n  ) +\n  scale_y_continuous(\n    name = \"Frequência\",\n    sec.axis = sec_axis(\n      ~ . / fator_escala,\n      name = \"Percentual acumulado (%)\",\n      breaks = tab_pareto$percentual_acumulado,\n      labels = paste0(\n      tab_pareto$percentual_acumulado,\n      \"%\"\n      )\n    )\n  ) +\n  labs(\n    title = \"Gráfico de Pareto — meio de transporte\",\n    x = \"Meio de transporte\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(\n      angle = 35,\n      hjust = 1\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\nEm um relatório mais elaborado, a linha de percentual acumulado pode ser adicionada com uma segunda escala. Para esta etapa introdutória, é mais importante compreender **como a ordenação e o acumulado são produzidos** do que acrescentar complexidade gráfica.\n\nUm **gráfico de setores** pode ser construído a partir da mesma tabela:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_transporte |>\n  ggplot(\n    aes(x = \"\", y = fi, fill = meio_transporte)\n  ) +\n  geom_col(width = 1) +\n  coord_polar(theta = \"y\") +\n  labs(\n    title = \"Composição dos meios de transporte\",\n    x = NULL,\n    y = NULL,\n    fill = \"Transporte\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\nCompare os dois gráficos. Para identificar rapidamente qual categoria é maior e comparar magnitudes, o gráfico de barras tende a ser mais eficiente. O gráfico de setores enfatiza a ideia de composição do total.\n\n### Variável qualitativa ordinal\n\nConsidere agora o nível de satisfação de 40 participantes:\n\n| Satisfação         |  $f_i$ | $f_{r_i}$ | Percentual |\n|:-------------------|-------:|----------:|-----------:|\n| Muito insatisfeito |      3 |     0,075 |       7,5% |\n| Insatisfeito       |      5 |     0,125 |      12,5% |\n| Indiferente        |      8 |     0,200 |      20,0% |\n| Satisfeito         |     16 |     0,400 |      40,0% |\n| Muito satisfeito   |      8 |     0,200 |      20,0% |\n| **Total**          | **40** | **1,000** | **100,0%** |\n\nAgora existe uma ordem natural:\n\n$$\\text{Muito insatisfeito}\n<\n\\text{Insatisfeito}\n<\n\\text{Indiferente}\n<\n\\text{Satisfeito}\n<\n\\text{Muito satisfeito}.$$\n\nPor isso, a frequência acumulada possui interpretação:\n\n| Satisfação         | $f_i$ | $F_i$ | $F_{\\%i}$ |\n|:-------------------|------:|------:|----------:|\n| Muito insatisfeito |     3 |     3 |      7,5% |\n| Insatisfeito       |     5 |     8 |     20,0% |\n| Indiferente        |     8 |    16 |     40,0% |\n| Satisfeito         |    16 |    32 |     80,0% |\n| Muito satisfeito   |     8 |    40 |    100,0% |\n\nPodemos dizer:\n\n> 40% dos participantes declararam satisfação no máximo até o nível \"indiferente\".\n\nou, de maneira mais natural:\n\n> 40% dos participantes declararam-se muito insatisfeitos, insatisfeitos ou indiferentes.\n\nNo gráfico de barras de uma variável ordinal, a **ordem natural das categorias deve ser preservada**. Ordenar simplesmente da maior para a menor frequência pode destruir parte da informação contida na variável.\n\n![Nível de satisfação dos estudantes](images/graficodecolunasordinal2.png)\n\n#### Valores ausentes e denominador\n\nSuponha que 42 pessoas tenham sido entrevistadas, mas duas não tenham respondido à pergunta de satisfação. Podemos informar:\n\n``` text\nTotal de participantes: 42\nRespostas válidas: 40\nNão informado: 2\n```\n\nSe os percentuais forem calculados entre as respostas válidas, o denominador é `40`. Se forem calculados sobre todos os participantes, o denominador é `42`. As duas opções respondem a perguntas diferentes.\n\n::: {.callout-note title=\"Sempre saiba qual é o denominador\"}\nUm percentual não deve ser interpretado sem saber qual total foi utilizado em seu cálculo. Em relatórios, informe claramente se os percentuais se referem ao total de registros ou apenas às respostas válidas.\n:::\n\n::: {.callout-tip title=\"Da teoria à prática\"}\nA tabela e os gráficos acima foram construídos para compreender a lógica estatística. No **Laboratório no R**, reproduziremos as mesmas ideias computacionalmente. O objetivo do código é automatizar procedimentos já compreendidos, não substituir sua interpretação.\n:::\n\n#### Laboratório no R\n\nA seguir, reproduzimos no R a organização da variável ordinal, preservando explicitamente a ordem das categorias.\n\nPara reproduzir o gráfico da Seção 1.1.3, escrevemos a tabela no R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_satisfacao <- tibble(\n  satisfacao = c(\n    \"Muito insatisfeito\",\n    \"Insatisfeito\",\n    \"Indiferente\",\n    \"Satisfeito\",\n    \"Muito satisfeito\"\n  ),\n  fi = c(3, 5, 8, 16, 8),\n  Fi = c(3, 8, 16, 32, 40),\n  F_percentual = c(7.5, 20, 40, 80, 100)\n) |>\n  mutate(\n    satisfacao = factor(\n      satisfacao,\n      levels = c(\n        \"Muito insatisfeito\",\n        \"Insatisfeito\",\n        \"Indiferente\",\n        \"Satisfeito\",\n        \"Muito satisfeito\"\n      ),\n      ordered = TRUE\n    )\n  )\n```\n:::\n\n\n\n\nE o **gráfico de colunas**,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_satisfacao |>\n  ggplot(\n    aes(\n      x = satisfacao,\n      y = fi\n    )\n  ) +\n  geom_col() +\n  labs(\n    title = \"Nível de satisfação dos estudantes\",\n    x = NULL,\n    y = \"Frequência\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(\n      angle = 35,\n      hjust = 1\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\nCaso queira mostrar a frequência sobre cada coluna:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_satisfacao |>\n  ggplot(\n    aes(\n      x = satisfacao,\n      y = fi\n    )\n  ) +\n  geom_col() +\n  geom_text(\n    aes(label = fi),\n    vjust = -0.4\n  ) +\n  labs(\n    title = \"Nível de satisfação dos estudantes\",\n    x = NULL,\n    y = \"Frequência\"\n  ) +\n  scale_y_continuous(\n    expand = expansion(mult = c(0, 0.12))\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(\n      angle = 35,\n      hjust = 1\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\nA seguir, construiremos o gráfico para a variável `satisfacao` do banco de dados `estudantes`. A variável deve ser explicitamente organizada como fator ordinal:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- dados |>\n  mutate(\n    satisfacao = factor(\n      satisfacao,\n      levels = c(\n        \"Muito baixa\",\n        \"Baixa\",\n        \"Média\",\n        \"Alta\",\n        \"Muito alta\"\n      ),\n      ordered = TRUE\n    )\n  )\n\nlevels(dados$satisfacao)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Muito baixa\" \"Baixa\"       \"Média\"       \"Alta\"        \"Muito alta\" \n```\n\n\n:::\n:::\n\n\n\n\nAgora construímos a tabela:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_satisfacao <- dados |>\n  filter(!is.na(satisfacao)) |>\n  count(satisfacao, name = \"fi\", .drop = FALSE) |>\n  mutate(\n    fr = fi / sum(fi),\n    percentual = 100 * fr,\n    Fi = cumsum(fi),\n    Fr = cumsum(fr)\n  )\n\ntab_satisfacao\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  satisfacao     fi    fr percentual    Fi    Fr\n  <ord>       <int> <dbl>      <dbl> <int> <dbl>\n1 Muito baixa     4 0.05         5       4 0.05 \n2 Baixa           9 0.112       11.2    13 0.162\n3 Média          24 0.3         30      37 0.462\n4 Alta           30 0.375       37.5    67 0.838\n5 Muito alta     13 0.162       16.2    80 1    \n```\n\n\n:::\n:::\n\n\n\n\nA ordem do fator é usada tanto na tabela acumulada quanto no gráfico:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_satisfacao |>\n  ggplot(\n    aes(x = satisfacao, y = percentual)\n  ) +\n  geom_col() +\n  labs(\n    title = \"Nível de satisfação\",\n    x = \"Satisfação\",\n    y = \"Percentual (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\nOrdenar esse gráfico da maior para a menor frequência destruiria a ordem substantiva da variável.\n\n### Variável quantitativa discreta\n\nConsidere um estudo com 25 empresas de porte médio. A variável $X$ representa o **número de empregados do setor de vendas com curso superior completo**.\n\nOs dados brutos são:\n\n$$4,\\ 1,\\ 2,\\ 5,\\ 3,\\ 1,\\ 0,\\ 2,\\ 4,\\ 3,\\\n2,\\ 3,\\ 0,\\ 1,\\ 4,\\ 3,\\ 2,\\ 3,\\ 1,\\ 2,\\\n1,\\ 2,\\ 4,\\ 3,\\ 2.$$\n\nA primeira pergunta é:\n\n> Quais valores foram observados?\n\nConstruindo o rol:\n\n$$0,\\ 0,$$\n\n$$1,\\ 1,\\ 1,\\ 1,\\ 1,$$\n\n$$2,\\ 2,\\ 2,\\ 2,\\ 2,\\ 2,\\ 2,$$\n\n$$3,\\ 3,\\ 3,\\ 3,\\ 3,\\ 3,$$\n\n$$4,\\ 4,\\ 4,\\ 4,$$\n\n$$5.$$\n\nOs valores observados são $0,1,2,3,4,5$.\n\nContando cada valor:\n\n|     $x_i$ |  $f_i$ |\n|----------:|-------:|\n|         0 |      2 |\n|         1 |      5 |\n|         2 |      7 |\n|         3 |      6 |\n|         4 |      4 |\n|         5 |      1 |\n| **Total** | **25** |\n\nAgora calculamos:\n\n$$f_{r_i}=\\frac{f_i}{25}.$$\n\nPara $x=3$:\n\n$$f_r(3)=\\frac{6}{25}=0{,}24.$$\n\nPortanto, 24% das empresas possuem **exatamente 3 empregados** com curso superior completo no setor considerado.\n\nA distribuição completa é:\n\n|     $x_i$ |  $f_i$ | $f_{r_i}$ | $f_{\\%i}$ | $F_i$ | $F_{r_i}$ | $F_{\\%i}$ |\n|----------:|-------:|----------:|----------:|------:|----------:|----------:|\n|         0 |      2 |      0,08 |        8% |     2 |      0,08 |        8% |\n|         1 |      5 |      0,20 |       20% |     7 |      0,28 |       28% |\n|         2 |      7 |      0,28 |       28% |    14 |      0,56 |       56% |\n|         3 |      6 |      0,24 |       24% |    20 |      0,80 |       80% |\n|         4 |      4 |      0,16 |       16% |    24 |      0,96 |       96% |\n|         5 |      1 |      0,04 |        4% |    25 |      1,00 |      100% |\n| **Total** | **25** |  **1,00** |  **100%** |       |           |           |\n\n: Distribuição de frequências do número de empregados com ensino superior completo.\n\nVamos interpretar algumas linhas.\n\nPara $x=0$:\n\n> 2 empresas não possuem empregado com curso superior completo no setor considerado, correspondendo a 8% das empresas.\n\nPara $x=2$:\n\n> 7 empresas possuem exatamente 2 empregados com curso superior completo, correspondendo a 28% das empresas.\n\nPara a frequência acumulada em $x=2$:\n\n$$F(2)=14.$$\n\nPara $x=3$:\n\n$$f_r(3)=\\frac{6}{25}=0{,}24.$$\n\nPortanto, 24% das empresas possuem exatamente três empregados com curso superior completo no setor considerado.\n\nA frequência acumulada em $x=2$ é:\n\n$$F(2)=14,$$ Logo:\n\n> 14 das 25 empresas possuem no máximo 2 empregados com curso superior completo.\n\nEm percentual:\n\n$$F_{r_i}(2){\\%}=56\\%.$$\n\nlogo 56% das empresas possuem **no máximo dois empregados** com curso superior completo.\n\nPara \"pelo menos três\" empregados:\n\n$$f(3)+f(4)+f(5)=6+4+1=11,$$\n\nportanto:\n\n$$\\frac{11}{25}=0{,}44=44\\%.$$\n\n#### Gráfico de barras para uma variável discreta\n\nUma variável quantitativa discreta também pode ser representada por barras. Nesse caso, cada barra corresponde a um **valor numérico distinto** e sua altura representa a frequência.\n\nA ordem numérica deve ser preservada. Diferentemente das categorias nominais, não faria sentido reorganizar `0,1,2,3,4,5` em ordem decrescente de frequência se o objetivo é representar a distribuição da variável.\n\nA seguir, construímos o gráfico de barras correspondente à distribuição de frequências. Como a variável é quantitativa discreta, cada valor observado é representado por uma barra separada, cuja altura corresponde à sua frequência absoluta.\n\n![Distribuição de frequências do número de empregados com ensino superior completo](images/graficodecolunasdiscreta2.png)\n\nNeste caso, o gráfico deixa evidente que $x_i=2$ é o valor mais frequente, com $f_i=7$.\n\n#### Gráfico de pontos\n\nO **gráfico de pontos** (*dot plot*) representa cada observação por um ponto. Valores repetidos são empilhados. Para conjuntos pequenos ou moderados, ele preserva uma visão muito próxima dos dados individuais e evidencia repetições sem exigir uma tabela extensa.\n\nNo exemplo das 25 empresas, uma coluna de sete pontos sobre o valor `2` mostra imediatamente que esse é o valor mais frequente.\n\n![Gráfico de pontos — número de faltas](images/graficodepontosdiscreta1.png)\n\n::: {.callout-tip title=\"Da teoria à prática\"}\nA tabela e os gráficos acima foram construídos para compreender a lógica estatística. No **Laboratório no R**, reproduziremos as mesmas ideias computacionalmente. O objetivo do código é automatizar procedimentos já compreendidos, não substituir sua interpretação.\n:::\n\n#### Laboratório no R\n\nPara o exemplo da variável `número de empregados com ensino superior completo`. Primeiro, podemos representar a tabela no R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_discreta <- tibble(\n  xi = 0:5,\n  fi = c(2, 5, 7, 6, 4, 1)\n)\n\ntab_discreta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n     xi    fi\n  <int> <dbl>\n1     0     2\n2     1     5\n3     2     7\n4     3     6\n5     4     4\n6     5     1\n```\n\n\n:::\n:::\n\n\n\n\nE o gráfico, no mesmo estilo que estamos usando:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_discreta |>\n  ggplot(\n    aes(\n      x = xi,\n      y = fi\n    )\n  ) +\n  geom_col(\n    width = 0.7\n  ) +\n  geom_text(\n    aes(label = fi),\n    vjust = -0.4\n  ) +\n  scale_x_continuous(\n    breaks = 0:5\n  ) +\n  scale_y_continuous(\n    breaks = 0:7,\n    expand = expansion(mult = c(0, 0.12))\n  ) +\n  labs(\n    title = \"Distribuição de frequências\",\n    x = expression(x[i]),\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\nAgora reproduzimos computacionalmente a distribuição de frequências e as representações gráficas da variável quantitativa discreta \\`faltas\\`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_faltas <- dados |>\n  filter(!is.na(faltas)) |>\n  count(faltas, name = \"fi\") |>\n  arrange(faltas) |>\n  mutate(\n    fr = fi / sum(fi),\n    percentual = 100 * fr,\n    Fi = cumsum(fi),\n    Fr = cumsum(fr)\n  )\n\ntab_faltas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 6\n  faltas    fi     fr percentual    Fi    Fr\n   <dbl> <int>  <dbl>      <dbl> <int> <dbl>\n1      0     4 0.05         5        4 0.05 \n2      1    24 0.3         30       28 0.35 \n3      2    24 0.3         30       52 0.65 \n4      3    19 0.238       23.8     71 0.888\n5      4     5 0.0625       6.25    76 0.95 \n6      5     3 0.0375       3.75    79 0.987\n7      6     1 0.0125       1.25    80 1    \n```\n\n\n:::\n:::\n\n\n\n\nA ordem numérica aparece antes de `cumsum()` porque a frequência acumulada depende da ordem dos valores.\n\nPodemos responder diretamente a algumas perguntas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exatamente 2 faltas\nsum(dados$faltas == 2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# No máximo 2 faltas\nsum(dados$faltas <= 2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52\n```\n\n\n:::\n\n```{.r .cell-code}\n# Pelo menos 3 faltas\nsum(dados$faltas >= 3, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n:::\n\n\n\n\nO gráfico de barras é:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_faltas |>\n  ggplot(\n    aes(x = factor(faltas), y = fi)\n  ) +\n  geom_col() +\n  labs(\n    title = \"Distribuição do número de faltas\",\n    x = \"Número de faltas\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n\nA seguir, construímos o gráfico de pontos correspondente à distribuição de frequências. Cada ponto representa uma empresa, e os pontos são empilhados quando duas ou mais empresas apresentam o mesmo número de empregados com ensino superior completo.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_discreta <- tibble(\n  xi = 0:5,\n  fi = c(2, 5, 7, 6, 4, 1)\n)\n```\n:::\n\n\n\n\nO gráfico de pontos pode ser construído assim:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_discreta |>\n  tidyr::uncount(fi) |>\n  ggplot(\n    aes(x = xi)\n  ) +\n  geom_dotplot(\n    binwidth = 1,\n    stackdir = \"up\",\n    dotsize = 0.4\n  ) +\n  scale_x_continuous(\n    breaks = 0:5\n  ) +\n  labs(\n    title = \"Gráfico de pontos — empregados com ensino superior completo\",\n    x = \"Número de empregados com ensino superior completo\",\n    y = NULL\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n\nPara a variável `faltas`, o gráfico de pontos permite visualizar como as observações se distribuem entre os diferentes números de faltas, preservando uma representação próxima dos dados individuais:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = faltas)\n  ) +\n  geom_dotplot(\n    binwidth = 1,\n    stackdir = \"up\",\n    dotsize = 0.15\n  ) +\n  labs(\n    title = \"Gráfico de pontos — número de faltas\",\n    x = \"Número de faltas\",\n    y = NULL\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\n### Apresentação e interpretação de tabelas\n\nUma tabela de frequências deve ser legível e responder ao problema em estudo.\n\n**Título.** Deve informar claramente qual variável está sendo apresentada e, quando necessário, qual grupo foi analisado.\n\n> Tabela 1 — Frequências\n\nprefira:\n\n> Tabela 1 — Distribuição do número de empregados com curso superior completo em 25 empresas de porte médio.\n\n**Categorias e valores.** Use rótulos claros e preserve ordens substantivas quando existirem. Evite códigos como `1`, `2`, `3` quando o leitor precisa consultar outro lugar para descobrir seu significado.\n\n**Casas decimais.** Utilize precisão suficiente para interpretar os resultados, sem excesso de dígitos.\n\nara uma turma de 20 estudantes, escrever:\n\n``` text\n30,000000%\n```\n\nnão acrescenta informação em relação a:\n\n``` text\n30,0%\n```\n\nou simplesmente:\n\n``` text\n30%\n```\n\n**Total.** Em geral, inclua a linha de total para permitir a verificação da tabela.\n\n**Fonte.** Quando os dados forem externos, informe sua origem.\n\n**Frequência acumulada.** Use somente quando a ordem das categorias ou valores tiver significado.\n\n**Valores ausentes.** Informe se foram excluídos do denominador ou apresentados separadamente.\n\nConsidere:\n\n| Faltas | $f_i$ | Percentual |\n|-------:|------:|-----------:|\n|      2 |     6 |        30% |\n\nUma interpretação fraca seria:\n\n> A frequência é 6.\n\nUma interpretação melhor seria:\n\n> Dos 20 estudantes observados, 6 apresentaram exatamente duas faltas, o que corresponde a 30% do grupo.\n\nEla informa:\n\n- quem está sendo analisado;\n- qual valor da variável;\n- qual contagem;\n- qual percentual;\n- qual denominador implícito.\n\n::: {.callout-tip title=\"A tabela mostra; o texto interpreta\"}\nNão é necessário repetir em prosa cada número da tabela. Destaque os padrões mais relevantes: categoria predominante, concentração dos valores, proporções particularmente altas ou baixas e resultados diretamente relacionados à pergunta de interesse.\n:::\n\n#### Laboratório no R\n\nA etapa final consiste em preparar a tabela para apresentação e, quando necessário, exportá-la. Os cálculos devem ser mantidos com sua precisão original; o arredondamento fica para a exibição.\n\nArredonde apenas para apresentação. Preserve os valores completos nos objetos usados em cálculos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_faltas_apresentacao <- tab_faltas |>\n  mutate(\n    fr = round(fr, 3),\n    percentual = round(percentual, 1),\n    Fr = round(Fr, 3)\n  )\n\nknitr::kable(\n  tab_faltas_apresentacao,\n  col.names = c(\n    \"Faltas\",\n    \"fi\",\n    \"fr\",\n    \"Percentual (%)\",\n    \"Fi\",\n    \"Fr\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n\n| Faltas| fi|    fr| Percentual (%)| Fi|    Fr|\n|------:|--:|-----:|--------------:|--:|-----:|\n|      0|  4| 0.050|            5.0|  4| 0.050|\n|      1| 24| 0.300|           30.0| 28| 0.350|\n|      2| 24| 0.300|           30.0| 52| 0.650|\n|      3| 19| 0.238|           23.8| 71| 0.887|\n|      4|  5| 0.062|            6.2| 76| 0.950|\n|      5|  3| 0.038|            3.8| 79| 0.987|\n|      6|  1| 0.013|            1.2| 80| 1.000|\n\n\n:::\n:::\n\n\n\n\nPara exportar:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv(\n  tab_faltas,\n  \"dados/tabela_faltas.csv\"\n)\n```\n:::\n\n\n\n\nA lógica pode ser reproduzida em uma planilha eletrônica. Se uma coluna contém os valores e outra lista as categorias ou valores distintos, funções do tipo `CONT.SE`, `SOMA` e fórmulas de divisão permitem calcular $f_i$, $f_{r_i}$ e percentuais. O princípio estatístico é o mesmo; muda apenas a ferramenta.\n\n::: {.callout-important title=\"O computador calcula; você interpreta\"}\n`count()`, `mutate()` e `cumsum()` automatizam cálculos, mas não decidem se uma frequência acumulada faz sentido, qual denominador deve ser usado ou como o resultado deve ser interpretado. Essas decisões pertencem ao analista.\n:::\n\n## Variáveis quantitativas contínuas\n\nUma variável quantitativa contínua pode assumir, em princípio, qualquer valor dentro de um intervalo. Se apresentarmos uma linha para cada valor observado, uma tabela de frequências pode ficar longa e pouco informativa. Nesse contexto, é comum **agrupar valores próximos em intervalos de classe**.\n\n### Distribuições por classes e representações gráficas\n\n#### Por que agrupar dados contínuos?\n\nConsidere alguns valores de tempo de deslocamento, em minutos:\n\n$$37{,}9,\\ 39{,}2,\\ 42{,}6,\\ 45{,}1,\\ 47{,}8,\\ 51{,}3,\\ 54{,}7,\\ 61{,}2,\\ 68{,}5,\\ 79{,}4.$$\n\nUma tabela contendo uma linha para cada valor teria pouca capacidade de síntese. Podemos agrupar valores próximos em **classes** e contar quantas observações pertencem a cada intervalo.\n\n::: {.callout-note title=\"Agrupar é resumir\"}\nAo agrupar dados contínuos em classes, ganhamos uma visão compacta da distribuição, mas perdemos parte da informação individual. Sabemos quantas observações existem em cada intervalo, mas não recuperamos os valores exatos apenas a partir da tabela agrupada.\n:::\n\n#### Amplitude total\n\nA **amplitude total** é a diferença entre o maior e o menor valor observado:\n\n$$A=x_{\\max}-x_{\\min}.$$\n\nSe o menor tempo for $11{,}7$ minutos e o maior $112{,}0$ minutos:\n\n$$A=112{,}0-11{,}7=100{,}3.$$\n\n::: {.callout-important title=\"Amplitude total não é amplitude de classe\"}\nA **amplitude total** descreve a extensão de todo o conjunto de dados. A **amplitude de classe** descreve a largura de um único intervalo da tabela.\n:::\n\n#### Classes, limites e amplitude de classe\n\nUma **classe** é um intervalo utilizado para reunir observações próximas. Por exemplo:\n\n$$[10;25).$$\n\nEssa notação significa:\n\n$$10\\leq x<25.$$\n\nO limite inferior está incluído e o limite superior não está. Assim, `10` pertence à classe $[10;25)$, enquanto `25` pertence à classe seguinte.\n\nA amplitude ou largura da classe é:\n\n$$h=L_s-L_i,$$\n\nem que $L_i$ e $L_s$ representam os limites inferior e superior.\n\nPara $[10;25)$:\n\n$$h=25-10=15.$$\n\nClasses bem construídas devem evitar sobreposição, lacunas e ambiguidades.\n\n#### Ponto médio da classe\n\nO ponto médio é:\n\n$$x_i=\\frac{L_i+L_s}{2}.$$\n\nPara $[10;25)$:\n\n$$x_i=\\frac{10+25}{2}=17{,}5.$$\n\nO ponto médio representa a posição central do intervalo, mas não significa que todas as observações da classe sejam iguais a ele.\n\n#### Quantas classes utilizar?\n\nNão existe um único número correto de classes para todos os conjuntos de dados. Poucas classes podem esconder características importantes; classes demais podem produzir um resumo irregular e excessivamente sensível a pequenas flutuações.\n\nAs regras a seguir fornecem **pontos de partida**, e não respostas automáticas.\n\n##### Regra da raiz quadrada\n\n$$k\\approx\\sqrt{n}.$$\n\nPara $n=80$:\n\n$$k\\approx\\sqrt{80}\\approx8{,}94,$$\n\nsugerindo cerca de 9 classes.\n\n##### Regra de Sturges\n\nA regra de Sturges pode ser escrita como:\n\n$$k=1+\\log_2(n),$$\n\nou, de forma equivalente,\n\n$$k=1+3{,}322\\log_{10}(n).$$\n\nPara $n=80$:\n\n$$k\\approx7{,}32.$$\n\nUm arredondamento prático conduz a aproximadamente 8 classes.\n\n##### Regra de Scott\n\nScott propôs uma regra para a largura de classe:\n\n$$h_{\\text{Scott}}=3{,}5\\,s\\,n^{-1/3},$$\n\nem que $s$ é o desvio-padrão amostral.\n\nPara os tempos de deslocamento utilizados neste capítulo, $s\\approx21{,}57$:\n\n$$h_{\\text{Scott}}\\approx17{,}52.$$\n\nComo $A\\approx100{,}3$:\n\n$$k\\approx\\frac{100{,}3}{17{,}52}\\approx5{,}72,$$\n\nou cerca de 6 classes.\n\n##### Regra de Freedman--Diaconis\n\nA regra de Freedman--Diaconis utiliza a amplitude interquartil:\n\n$$h_{\\text{FD}}=2\\,AIQ\\,n^{-1/3},$$\n\ncom\n\n$$AIQ=Q_3-Q_1.$$\n\nPara os mesmos dados:\n\n$$Q_1\\approx24{,}675,\n\\qquad\nQ_3\\approx51{,}775,$$\n\nportanto,\n\n$$AIQ=27{,}1.$$\n\nLogo,\n\n$$h_{\\text{FD}}\\approx12{,}58,$$\n\nque corresponde a aproximadamente 8 classes.\n\nComo utiliza a amplitude interquartil, essa regra tende a ser menos sensível a valores extremos do que uma regra baseada no desvio-padrão.\n\n##### Comparando as propostas\n\n| Regra              |               Resultado aproximado |\n|:-------------------|-----------------------------------:|\n| Raiz quadrada      |                          9 classes |\n| Sturges            |                          8 classes |\n| Scott              | largura 17,52 → cerca de 6 classes |\n| Freedman--Diaconis | largura 12,58 → cerca de 8 classes |\n\nAs regras não concordam perfeitamente — e isso é esperado.\n\n::: {.callout-important title=\"As regras são referências, não leis\"}\nA decisão final deve considerar tamanho da amostra, distribuição dos dados, unidade de medida, objetivo da análise e clareza da representação. Pergunte menos “qual fórmula está certa?” e mais “qual organização revela a estrutura dos dados sem esconder padrões nem exagerar pequenas irregularidades?”.\n:::\n\n#### Construindo uma tabela de frequências por classes: passo a passo\n\nUtilizaremos o **tempo de deslocamento até a universidade** de 80 estudantes. A mesma tabela será reproduzida no R no laboratório deste capítulo.\n\n##### Passo 1 — Identificar o número de observações e os extremos\n\nTemos:\n\n$$n=80,$$\n\n$$x_{\\min}=11{,}7,\n\\qquad\nx_{\\max}=112{,}0.$$\n\n##### Passo 2 — Calcular a amplitude total\n\n$$A=112{,}0-11{,}7=100{,}3.$$\n\n##### Passo 3 — Escolher um número inicial de classes\n\nAs regras anteriores sugeriram algo entre aproximadamente 6 e 9 classes. Como ponto de partida, adotaremos $k=8$.\n\n##### Passo 4 — Obter uma largura inicial e ajustá-la\n\nUma largura inicial pode ser calculada por:\n\n$$h\\approx\\frac{A}{k}.$$\n\nLogo,\n\n$$h\\approx\\frac{100{,}3}{8}=12{,}54.$$\n\nPara obter limites simples e fáceis de interpretar, adotaremos uma largura conveniente de **15 minutos**.\n\n::: {.callout-note title=\"Ajustar a largura pode alterar o número final de classes\"}\nEscolher $h=15$ em vez de $12{,}54$ faz com que o número final de classes deixe de ser exatamente 8. Isso não é um erro. As regras forneceram uma referência inicial; a tabela final deve também ser legível e cobrir todos os valores.\n:::\n\n##### Passo 5 — Definir os limites das classes\n\nEscolhemos um limite inferior simples, abaixo do mínimo observado: `10` minutos. Com largura 15:\n\n$$[10;25),\\ [25;40),\\ [40;55),\\ [55;70),$$\n\n$$[70;85),\\ [85;100),\\ [100;115).$$\n\nEssas sete classes cobrem todos os valores observados, do mínimo $11{,}7$ ao máximo $112{,}0$.\n\n##### Passo 6 — Calcular os pontos médios\n\n|   Classe    | Ponto médio |\n|:-----------:|------------:|\n|  $[10;25)$  |        17,5 |\n|  $[25;40)$  |        32,5 |\n|  $[40;55)$  |        47,5 |\n|  $[55;70)$  |        62,5 |\n|  $[70;85)$  |        77,5 |\n| $[85;100)$  |        92,5 |\n| $[100;115)$ |       107,5 |\n\n##### Passo 7 — Contar as observações em cada classe\n\nPercorremos os dados e registramos a classe de cada observação. As frequências absolutas obtidas são:\n\n|   Classe    |  $f_i$ |\n|:-----------:|-------:|\n|  $[10;25)$  |     21 |\n|  $[25;40)$  |     26 |\n|  $[40;55)$  |     16 |\n|  $[55;70)$  |     10 |\n|  $[70;85)$  |      3 |\n| $[85;100)$  |      3 |\n| $[100;115)$ |      1 |\n|  **Total**  | **80** |\n\n##### Passo 8 — Calcular frequências relativas e percentuais\n\nPara cada classe:\n\n$$f_{r_i}=\\frac{f_i}{80}.$$\n\nPara $[25;40)$:\n\n$$f_{r_i}=\\frac{26}{80}=0{,}325.$$\n\nPortanto, 32,5% dos estudantes apresentam tempo de deslocamento entre 25 minutos, inclusive, e 40 minutos, exclusive.\n\n##### Passo 9 — Calcular frequências acumuladas\n\nPara a segunda classe:\n\n$$F_i=21+26=47.$$\n\nIsso significa que 47 estudantes apresentam tempo de deslocamento inferior a 40 minutos.\n\n##### Passo 10 — Montar a tabela completa\n\n| Tempo de deslocamento (min) | Ponto médio | $f_i$ | $f_{r_i}$ | Percentual | $F_i$ | $F_{r_i}$ |\n|:----------|----------:|----------:|----------:|----------:|----------:|----------:|\n| $[10;25)$ | 17,5 | 21 | 0,2625 | 26,25% | 21 | 0,2625 |\n| $[25;40)$ | 32,5 | 26 | 0,3250 | 32,50% | 47 | 0,5875 |\n| $[40;55)$ | 47,5 | 16 | 0,2000 | 20,00% | 63 | 0,7875 |\n| $[55;70)$ | 62,5 | 10 | 0,1250 | 12,50% | 73 | 0,9125 |\n| $[70;85)$ | 77,5 | 3 | 0,0375 | 3,75% | 76 | 0,9500 |\n| $[85;100)$ | 92,5 | 3 | 0,0375 | 3,75% | 79 | 0,9875 |\n| $[100;115)$ | 107,5 | 1 | 0,0125 | 1,25% | 80 | 1,0000 |\n| **Total** | — | **80** | **1,0000** | **100%** | — | — |\n\n##### Passo 11 — Conferir a tabela\n\nUma tabela bem construída deve satisfazer:\n\n$$\\sum f_i=80,$$\n\n$$\\sum f_{r_i}=1,$$\n\n$$F_{\\text{última classe}}=80,$$\n\ne\n\n$$F_{r,\\text{última classe}}=1.$$\n\n##### Passo 12 — Interpretar, não apenas calcular\n\nA classe mais frequente é $[25;40)$, com 26 estudantes, correspondendo a 32,5% da amostra.\n\nA frequência acumulada até essa classe é 47, portanto:\n\n> 47 dos 80 estudantes, ou 58,75%, apresentam tempo de deslocamento inferior a 40 minutos.\n\nObserve a diferença:\n\n- `26` descreve **somente** a classe $[25;40)$;\n- `47` descreve tudo o que foi acumulado desde a primeira classe até menos de 40 minutos.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n#### Da tabela ao histograma\n\nDepois de construir a tabela, a passagem para o **histograma** é natural: cada classe se torna um intervalo no eixo horizontal e sua frequência determina a representação vertical.\n\nConsiderando a distribuição do tempo de deslocamento dos 80 estudantes, o histograma correspondente é apresentado na @fig-histograma-tempo.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Histograma do tempo de deslocamento (min).](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-histograma-tempo-1.png){#fig-histograma-tempo width=672}\n:::\n:::\n\n\n\n\nA @fig-histograma-tempo permite visualizar como os tempos de deslocamento se distribuem entre as classes. Observa-se maior concentração de estudantes nas classes de menores tempos de deslocamento, enquanto as frequências diminuem à medida que o tempo aumenta.\n\nDiferentemente do gráfico de barras, o histograma representa uma variável quantitativa em uma escala contínua. As barras são adjacentes porque os intervalos também são contíguos.\n\n##### Gráfico de barras × histograma\n\n| Gráfico de barras | Histograma |\n|:-----------------------------------|:-----------------------------------|\n| categorias ou valores discretos | intervalos de uma variável quantitativa |\n| barras geralmente separadas | retângulos adjacentes |\n| ordem pode ser arbitrária em variáveis nominais | ordem numérica é obrigatória |\n| largura da barra não representa uma amplitude de valores | largura representa um intervalo da escala |\n\n::: {.callout-important title=\"Histograma não é apenas um gráfico de barras com barras encostadas\"}\nOs dois gráficos representam estruturas diferentes. No histograma, cada retângulo corresponde a um intervalo numérico da variável.\n:::\n\n##### A área dos retângulos\n\nQuando todas as classes possuem a mesma largura, comparar alturas é suficiente para comparar frequências. Se as classes tiverem larguras diferentes, a interpretação correta exige que a **área** de cada retângulo seja proporcional à frequência. Nesse caso, utiliza-se uma densidade de frequência na altura do retângulo. A densidade de frequência de uma classe pode ser definida como: $$d_i = \\frac{f_i}{h_i}$$ em que $h_i$ é a largura da classe.\n\nAssim: $$\\text{área} = h_i \\times d_i = f_i$$ á\n\nEssa observação será importante quando compararmos histogramas com curvas de densidade.\n\nA @fig-histograma-amplitude-diferente-tempo apresenta o histograma adaptado do tempo de deslocamento, construído com classes de amplitudes diferentes.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Histograma com amplitudes de classes diferente do tempo de deslocamento, com classes de amplitudes diferentes.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-histograma-amplitude-diferente-tempo-1.png){#fig-histograma-amplitude-diferente-tempo width=672}\n:::\n:::\n\n\n\n\nNo histograma adaptado do tempo de deslocamento, observa-se maior concentração de estudantes na classe \\[25, 40) minutos, que apresenta a maior densidade de frequência. As classes \\[10, 25) e \\[40, 55) também apresentam densidades relativamente elevadas. A partir de 55 minutos, as classes foram construídas com amplitude maior, de 30 minutos, e apresentam alturas menores. Nesse caso, a altura dos retângulos não deve ser interpretada diretamente como frequência: é a área de cada retângulo que representa a frequência da classe. Assim, uma classe mais larga pode conter um número considerável de observações e, ainda assim, apresentar uma altura menor.\n\nVale a pena destacar um exemplo concreto. Na classe\n\n$$ [40,55), $$\n\ntemos (16) estudantes e amplitude (15), portanto:\n\n$$ d_i=\\frac{16}{15}\\approx1{,}07. $$\n\nJá na classe mais larga\n\n$$ [55,85), $$\n\ntemos (13) estudantes, mas amplitude (30):\n\n$$ d_i=\\frac{13}{30}\\approx0{,}43. $$\n\nPortanto, embora 13 estudantes estejam entre 55 e 85 minutos, o retângulo é consideravelmente mais baixo porque essas observações estão distribuídas em um intervalo duas vezes mais largo.\n\nNo histograma com classes de amplitudes diferentes, não se deve comparar as frequências pela altura dos retângulos. A comparação correta é feita pelas áreas, pois a área de cada retângulo é proporcional à frequência da respectiva classe.\n\n#### O efeito da escolha das classes\n\nO mesmo conjunto de dados pode produzir histogramas visualmente diferentes conforme o número e a largura das classes.\n\n- poucas classes podem esconder características relevantes;\n- muitas classes podem produzir uma figura excessivamente irregular;\n- uma escolha intermediária procura revelar estrutura sem destacar ruído desnecessário.\n\nPor isso, a escolha das classes é uma **decisão exploratória**.\n\n#### Polígono de frequências\n\nO polígono de frequências é construído ligando pontos cujas coordenadas são:\n\n- no eixo horizontal: **pontos médios das classes**;\n- no eixo vertical: frequências das classes.\n\nAssim, os pontos médios calculados na tabela passam a ter uma função gráfica direta.\n\nPara as primeiras classes:\n\n$$(17{,}5;21),\\quad(32{,}5;26),\\quad(47{,}5;16),\\ldots$$\n\nO polígono oferece uma leitura do formato geral da distribuição e pode facilitar comparações entre distribuições.\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Polígono de frequência do tempo de deslocamento (min).](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-poligono-tempo-1.png){#fig-poligono-tempo width=672}\n:::\n:::\n\n\n\n\n#### Ogiva\n\nA **ogiva** representa frequências acumuladas. Uma forma comum é utilizar:\n\n- no eixo horizontal: limites superiores das classes;\n- no eixo vertical: $F_i$, $F_{r_i}$ ou percentual acumulado.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Ogiva do tempo de deslocamento.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-ogiva-tempo-1.png){#fig-ogiva-tempo width=672}\n:::\n:::\n\n\n\n\nA partir da tabela anterior, o ponto associado ao limite `40` possui frequência acumulada `47`. Portanto, a ogiva permite visualizar perguntas do tipo:\n\n> quantas observações estão abaixo de determinado valor?\n\nEssa ideia será especialmente útil quando estudarmos medidas de posição.\n\n#### Diagrama de ramo e folhas\n\nO **diagrama de ramo e folhas** (*stem-and-leaf plot*) é uma representação utilizada para organizar dados quantitativos, permitindo visualizar a forma da distribuição sem perder completamente as observações individuais.\n\nA ideia consiste em dividir cada valor em duas partes:\n\n- o **ramo**, formado pelos algarismos iniciais;\n- a **folha**, formada pelo algarismo final.\n\nDiferentemente do histograma, no qual as observações são agrupadas em classes, o diagrama de ramo e folhas mantém visíveis os algarismos que compõem os valores observados.\n\n##### Construção manual\n\nConsidere os seguintes tempos, em minutos:\n\n$$12,\\ 13,\\ 14,\\ 14,\\ 15,\\ 17,\\ 18,\\ 21,\\ 22,\\ 22,\\ 25,\\ 27,\\ 31,\\ 34,\\ 36.$$\n\nComo os valores são inteiros e estão compreendidos entre 12 e 36 minutos, uma escolha simples consiste em utilizar:\n\n- a **dezena** como ramo;\n- a **unidade** como folha.\n\nAssim,\n\n$$12 = 1\\,|\\,2,$$\n\nisto é, o ramo é `1` e a folha é `2`.\n\nDa mesma forma,\n\n$$25 = 2\\,|\\,5$$\n\ne\n\n$$34 = 3\\,|\\,4.$$\n\nPrimeiro, identificamos os ramos necessários:\n\n``` text\n1 |\n2 |\n3 |\n```\n\nEm seguida, percorremos os dados e colocamos cada folha no ramo correspondente:\n\n``` text\n1 | 2 3 4 4 5 7 8\n2 | 1 2 2 5 7\n3 | 1 4 6\n```\n\nAs folhas são apresentadas em ordem crescente dentro de cada ramo.\n\n::: {.callout-tip title=\"Chave de leitura\"}\nÉ importante informar como o diagrama deve ser interpretado.\n\nNeste exemplo,\n\n``` text\n1 | 2\n```\n\nrepresenta\n\n$$12\\text{ minutos}.$$\n\nPortanto, a chave do diagrama pode ser escrita como\n\n$$1\\,|\\,2 = 12\\text{ minutos}.$$\n:::\n\nA linha\n\n``` text\n2 | 1 2 2 5 7\n```\n\nrepresenta, portanto, os valores\n\n$$21,\\ 22,\\ 22,\\ 25,\\ 27.$$\n\nObserve que as repetições também são preservadas. Como o valor 22 ocorreu duas vezes, aparecem duas folhas `2` no ramo `2`.\n\nO diagrama permite perceber simultaneamente os **valores observados** e algumas características da distribuição. Podemos identificar regiões de maior concentração, lacunas, dispersão, assimetria e possíveis valores muito afastados dos demais.\n\n::: {.callout-note title=\"A escolha do ramo e da folha\"}\nA separação entre ramo e folha depende da magnitude e da precisão dos dados.\n\nNo exemplo anterior, foi conveniente utilizar as dezenas como ramos e as unidades como folhas. Em outros conjuntos de dados, pode ser necessário utilizar centenas, unidades ou até casas decimais como referência.\n\nPor isso, todo diagrama de ramo e folhas deve apresentar uma **chave de leitura**.\n:::\n\nO diagrama de ramo e folhas é particularmente útil para conjuntos de dados pequenos ou moderados. Para conjuntos muito grandes, o número de folhas pode tornar a representação extensa e de difícil leitura.\n\nExemplo: tempo de deslocamento dos 80 estudantes\n\nConsidere agora a variável `tempo_deslocamento_min`, que registra o tempo de deslocamento, em minutos, dos 80 estudantes.\n\nAntes de utilizar uma representação gráfica, podemos organizar as observações em um **rol**:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  11.7  12.9  13.4  14.0  14.3  15.0  15.3  15.4  17.1  17.6  17.9  20.0\n[13]  20.1  21.6  21.9  22.0  22.3  24.1  24.4  24.6  24.7  25.5  26.3  26.7\n[25]  27.5  27.5  27.9  28.3  29.6  29.8  31.1  31.4  31.6  32.0  32.0  33.2\n[37]  34.2  34.3  34.3  35.7  36.3  37.7  38.1  38.1  38.6  38.6  38.8  40.7\n[49]  40.9  44.5  45.1  45.5  46.6  46.8  46.8  49.9  51.0  51.3  51.6  51.7\n[61]  52.0  52.5  52.8  56.5  56.8  58.2  61.1  63.3  66.7  66.8  68.5  68.6\n[73]  68.9  72.7  76.3  77.8  85.9  96.5  99.2 112.0\n```\n\n\n:::\n:::\n\n\n\n\nO rol preserva todos os valores e os apresenta em ordem crescente. Entretanto, com 80 observações, sua leitura já se torna menos imediata. O diagrama de ramo e folhas permite organizar esses valores de maneira mais compacta.\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n   1 | 23344555788\n   2 | 00222244556678888\n   3 | 0011222344466888999\n   4 | 11556777\n   5 | 01122233778\n   6 | 1377999\n   7 | 368\n   8 | 6\n   9 | 79\n  10 | \n  11 | 2\n```\n\n\n:::\n:::\n\n\n\n\nOutro pacote que produz o ramos e folhas é o `fmsb`:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagrama de ramo e folhas do tempo de deslocamento dos 80 estudantes.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-ramo-folhas-tempo-1.png){#fig-ramo-folhas-tempo width=672}\n:::\n:::\n\n\n\n\n#### Curva de densidade\n\nA **curva de densidade estimada** é uma representação suavizada da distribuição de uma variável quantitativa contínua. Em vez de dividir a escala em classes rígidas como o histograma, a densidade utiliza um procedimento de suavização para mostrar regiões de maior e menor concentração.\n\nA densidade não deve ser interpretada como uma tabela de frequências: sua escala vertical não corresponde diretamente ao número de observações. A área total sob a curva é igual a 1: $$\\int_{-\\infty}^{\\infty}\\hat f(x)\\,dx=1.$$\n\nA @fig-densidade-tempo apresenta uma versão suavizada da distribuição dos tempos de deslocamento. Observa-se maior concentração de estudantes nos menores e intermediários tempos de deslocamento, com o pico da densidade localizado aproximadamente na região entre 25 e 40 minutos. À medida que o tempo aumenta, a densidade tende a diminuir, permanecendo uma cauda mais prolongada à direita, associada aos estudantes com tempos de deslocamento mais elevados.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Curva de densidade do tempo de deslocamento dos 80 estudantes.](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/fig-densidade-tempo-1.png){#fig-densidade-tempo width=672}\n:::\n:::\n\n\n\n\nDiferentemente do histograma de frequências, a altura da curva não representa diretamente o número de estudantes. A curva descreve a **concentração relativa das observações ao longo dos valores da variável**, e a área total sob a curva é igual a 1.\n\n##### O papel da suavização\n\nA aparência da curva depende da **largura de banda** (*bandwidth*):\n\n- largura de banda muito pequena → curva excessivamente irregular;\n- largura de banda muito grande → curva excessivamente suavizada;\n- valores intermediários procuram revelar a estrutura principal.\n\nAssim como a largura das classes influencia um histograma, a largura de banda influencia uma curva de densidade.\n\n### Laboratório no R\n\nUtilizaremos exatamente a mesma variável `tempo_deslocamento_min` e reproduziremos a tabela construída manualmente.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- dados$tempo_deslocamento_min\n\nn <- sum(!is.na(x))\nx_min <- min(x, na.rm = TRUE)\nx_max <- max(x, na.rm = TRUE)\nA <- x_max - x_min\n\nc(\n  n = n,\n  minimo = x_min,\n  maximo = x_max,\n  amplitude = A\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        n    minimo    maximo amplitude \n     80.0      11.7     112.0     100.3 \n```\n\n\n:::\n:::\n\n\n\n\n#### Regras para número ou largura de classes\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_raiz <- ceiling(sqrt(n))\nk_raiz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nk_sturges <- ceiling(1 + log2(n))\nk_sturges\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code}\nnclass.Sturges(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nh_scott <- 3.5 * sd(x, na.rm = TRUE) * n^(-1/3)\nk_scott <- ceiling(A / h_scott)\n\nc(\n  largura_scott = h_scott,\n  numero_classes = k_scott\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n largura_scott numero_classes \n      17.52042        6.00000 \n```\n\n\n:::\n\n```{.r .cell-code}\nnclass.scott(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nh_fd <- 2 * IQR(x, na.rm = TRUE) * n^(-1/3)\nk_fd <- ceiling(A / h_fd)\n\nc(\n  largura_fd = h_fd,\n  numero_classes = k_fd\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    largura_fd numero_classes \n      12.57871        8.00000 \n```\n\n\n:::\n\n```{.r .cell-code}\nnclass.FD(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n\n\nCompare as propostas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  regra = c(\n    \"Raiz quadrada\",\n    \"Sturges\",\n    \"Scott\",\n    \"Freedman-Diaconis\"\n  ),\n  numero_classes = c(\n    k_raiz,\n    k_sturges,\n    k_scott,\n    k_fd\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  regra             numero_classes\n  <chr>                      <dbl>\n1 Raiz quadrada                  9\n2 Sturges                        8\n3 Scott                          6\n4 Freedman-Diaconis              8\n```\n\n\n:::\n:::\n\n\n\n\n#### Reproduzindo exatamente a tabela manual\n\nNa construção teórica adotamos limites de 10 a 115 minutos, com amplitude de 15 minutos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlimites <- seq(\n  from = 10,\n  to = 115,\n  by = 15\n)\n\nlimites\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  10  25  40  55  70  85 100 115\n```\n\n\n:::\n:::\n\n\n\n\nCriamos a estrutura das classes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestrutura_classes <- tibble(\n  limite_inferior = head(limites, -1),\n  limite_superior = tail(limites, -1)\n) |>\n  mutate(\n    ponto_medio =\n      (limite_inferior + limite_superior) / 2\n  )\n\nestrutura_classes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  limite_inferior limite_superior ponto_medio\n            <dbl>           <dbl>       <dbl>\n1              10              25        17.5\n2              25              40        32.5\n3              40              55        47.5\n4              55              70        62.5\n5              70              85        77.5\n6              85             100        92.5\n7             100             115       108. \n```\n\n\n:::\n:::\n\n\n\n\nClassificamos cada observação:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclasse <- cut(\n  x,\n  breaks = limites,\n  right = FALSE,\n  include.lowest = TRUE\n)\n\ntable(classe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclasse\n  [10,25)   [25,40)   [40,55)   [55,70)   [70,85)  [85,100) [100,115] \n       21        26        16        10         3         3         1 \n```\n\n\n:::\n:::\n\n\n\n\nO argumento `right = FALSE` produz intervalos fechados à esquerda e abertos à direita, como $[10;25)$.\n\nAgora calculamos as frequências:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfi <- as.integer(\n  table(classe)\n)\n\ntabela_classes <- estrutura_classes |>\n  mutate(\n    fi = fi,\n    fr = fi / sum(fi),\n    percentual = 100 * fr,\n    Fi = cumsum(fi),\n    Fr = cumsum(fr)\n  )\n\ntabela_classes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 8\n  limite_inferior limite_superior ponto_medio    fi     fr percentual    Fi\n            <dbl>           <dbl>       <dbl> <int>  <dbl>      <dbl> <int>\n1              10              25        17.5    21 0.262       26.2     21\n2              25              40        32.5    26 0.325       32.5     47\n3              40              55        47.5    16 0.2         20       63\n4              55              70        62.5    10 0.125       12.5     73\n5              70              85        77.5     3 0.0375       3.75    76\n6              85             100        92.5     3 0.0375       3.75    79\n7             100             115       108.      1 0.0125       1.25    80\n# ℹ 1 more variable: Fr <dbl>\n```\n\n\n:::\n:::\n\n\n\n\nPara apresentação:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_classes_apresentacao <- tabela_classes |>\n  mutate(\n    intervalo = paste0(\n      \"[\",\n      limite_inferior,\n      \"; \",\n      limite_superior,\n      \")\"\n    ),\n    fr = round(fr, 4),\n    `Percentual (%)` = round(percentual, 2),\n    `Fr acumulada` = round(Fr, 4)\n  ) |>\n  select(\n    intervalo,\n    ponto_medio,\n    fi,\n    fr,\n    `Percentual (%)`,\n    Fi,\n    `Fr acumulada`\n  )\n\nknitr::kable(\n  tabela_classes_apresentacao,\n  col.names = c(\n    \"Classe\",\n    \"Ponto médio\",\n    \"fi\",\n    \"fr\",\n    \"Percentual (%)\",\n    \"Fi\",\n    \"Fr\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n\n|Classe     | Ponto médio| fi|     fr| Percentual (%)| Fi|     Fr|\n|:----------|-----------:|--:|------:|--------------:|--:|------:|\n|[10; 25)   |        17.5| 21| 0.2625|          26.25| 21| 0.2625|\n|[25; 40)   |        32.5| 26| 0.3250|          32.50| 47| 0.5875|\n|[40; 55)   |        47.5| 16| 0.2000|          20.00| 63| 0.7875|\n|[55; 70)   |        62.5| 10| 0.1250|          12.50| 73| 0.9125|\n|[70; 85)   |        77.5|  3| 0.0375|           3.75| 76| 0.9500|\n|[85; 100)  |        92.5|  3| 0.0375|           3.75| 79| 0.9875|\n|[100; 115) |       107.5|  1| 0.0125|           1.25| 80| 1.0000|\n\n\n:::\n:::\n\n\n\n\nVerificações:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(tabela_classes$fi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(tabela_classes$fr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(tabela_classes$Fi, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(tabela_classes$Fr, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n\n\nEsperamos `80`, `1`, `80` e `1`, respectivamente.\n\n#### Histograma com as mesmas classes da tabela\n\nPara que o histograma corresponda à tabela manual, usamos largura 15 e fronteira 10:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_histogram(\n    binwidth = 15,\n    boundary = 10,\n    closed = \"left\",\n    color = \"black\",\n    linewidth = 0.6\n  )+\n  scale_x_continuous(\n    breaks = seq(\n      from = 10,\n      to = 115,\n      by = 15\n    )\n  ) +\n  labs(\n    title = \"Histograma do tempo de deslocamento\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n\n\nAgora tabela e histograma utilizam a mesma organização da escala.\n\nPodemos comparar outras escolhas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_histogram(\n    bins = k_sturges\n  ) +\n  labs(\n    title = \"Histograma pela regra de Sturges\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_histogram(\n    binwidth = h_fd\n  ) +\n  labs(\n    title = \"Histograma com largura de Freedman--Diaconis\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n\nSuponha que as duas últimas classes tenha amplitude igual a 30, enquanto as três primeiras é igual a 15.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlimites_adaptados <- c(\n  10, 25, 40, 55, 85, 115\n)\n\ndados |>\n  ggplot(\n    aes(\n      x = tempo_deslocamento_min,\n      y = after_stat(count / width)\n    )\n  ) +\n  geom_histogram(\n    breaks = limites_adaptados,\n    closed = \"left\",\n    color = \"white\",\n    linewidth = 0.8\n  ) +\n  scale_x_continuous(\n    breaks = limites_adaptados\n  ) +\n  labs(\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Densidade de frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n\n\nNão escolha mecanicamente o gráfico “mais bonito”. Compare as representações e observe quais características permanecem estáveis diante de pequenas mudanças nas classes.\n\n#### Polígono de frequências\n\nO polígono utiliza diretamente os pontos médios e as frequências da tabela:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_poligono <- tabela_classes |>\n  select(ponto_medio, fi) |>\n  bind_rows(\n    tibble(ponto_medio = 10, fi = 0),\n    tibble(ponto_medio = 115, fi = 0)\n  ) |>\n  arrange(ponto_medio)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_poligono |>\n  ggplot(\n    aes(x = ponto_medio, y = fi)\n  ) +\n  geom_line() +\n  geom_point() +\n  scale_x_continuous(\n    breaks = c(\n      10,\n      tabela_classes$ponto_medio,\n      115\n    )\n  )+\n  labs(\n    title = \"\",\n    x = \"Tempo de deslocamento (minutos)\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n\n\nPara fechar o polígono de frequências, acrescentamos dois pontos auxiliares com frequência zero: um no limite inferior da primeira classe e outro no limite superior da última classe. Esses pontos não representam novas classes; servem apenas para completar a representação gráfica.\n\nComo ficaria o polígono de frequências diretamente dos dados:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dados,\n  aes(x = tempo_deslocamento_min)\n) +\n  geom_freqpoly(\n    binwidth = 15,\n    boundary = 10\n  ) +\n  labs(\n    title = \"Polígono de frequências\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Frequência\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Ogiva\n\nPrimeiro associamos a cada classe seu limite superior e a frequência acumulada:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_ogiva <- tabela_classes |>\n  transmute(\n    limite_superior,\n    Fi,\n    percentual_acumulado = 100 * Fr\n  ) |>\n  bind_rows(\n    tibble(\n      limite_superior = 10,\n      Fi = 0,\n      percentual_acumulado = 0\n    )\n  ) |>\n  arrange(limite_superior)\n\ntabela_ogiva\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  limite_superior    Fi percentual_acumulado\n            <dbl> <dbl>                <dbl>\n1              10     0                  0  \n2              25    21                 26.2\n3              40    47                 58.8\n4              55    63                 78.8\n5              70    73                 91.3\n6              85    76                 95  \n7             100    79                 98.8\n8             115    80                100  \n```\n\n\n:::\n:::\n\n\n\n\nOgiva em frequência absoluta:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_ogiva |>\n  ggplot(\n    aes(\n      x = limite_superior,\n      y = Fi\n    )\n  ) +\n  geom_line() +\n  geom_point() +\n  scale_x_continuous(\n    breaks = seq(10, 115, by = 15)\n  ) +\n  labs(\n    title = \"Ogiva do tempo de deslocamento\",\n    x = \"Limite da classe (min)\",\n    y = \"Frequência acumulada\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n\n\nEm percentual acumulado:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_ogiva |>\n  ggplot(\n    aes(\n      x = limite_superior,\n      y = percentual_acumulado\n    )\n  ) +\n  geom_line() +\n  geom_point() +\n  scale_x_continuous(\n    breaks = seq(10, 115, by = 15)\n  ) +\n  scale_y_continuous(\n    breaks = seq(0, 100, by = 20)\n  ) +\n  labs(\n    title = \"Ogiva percentual do tempo de deslocamento\",\n    x = \"Limite da classe (min)\",\n    y = \"Percentual acumulado (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Função de distribuição empírica: uma observação útil\n\nA função de distribuição empírica utiliza diretamente os valores observados, sem agrupá-los em classes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  stat_ecdf() +\n  labs(\n    title = \"Função de distribuição empírica\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Proporção acumulada\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\n\n\nA ECDF e a ogiva têm em comum a ideia de acumulação, mas a ogiva apresentada anteriormente depende das classes escolhidas; a ECDF utiliza cada valor observado.\n\n#### Diagrama de ramo e folhas\n\nNo R, o diagrama de ramo e folhas pode ser obtido pela função `stem()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem(\n  dados$tempo_deslocamento_min\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n   0 | 23344555788\n   2 | 002222445566788880011222344466888999\n   4 | 1155677701122233778\n   6 | 1377999368\n   8 | 679\n  10 | 2\n```\n\n\n:::\n:::\n\n\n\n\nA função possui a forma básica\n\n``` r\nstem(\n  x,\n  scale = 1\n)\n```\n\nem que `x` é o vetor numérico e `scale` controla o **comprimento da representação**.\n\nPor padrão,\n\n``` r\nscale = 1\n```\n\ne, portanto, o comando\n\n``` r\nstem(dados$tempo_deslocamento_min)\n```\n\né equivalente a\n\n``` r\nstem(\n  dados$tempo_deslocamento_min,\n  scale = 1\n)\n```\n\nPara os tempos de deslocamento, obtemos:\n\n``` text\nThe decimal point is 1 digit(s) to the right of the |\n\n   0 | 23344555788\n   2 | 002222445566788880011222344466888999\n   4 | 1155677701122233778\n   6 | 1377999368\n   8 | 679\n  10 | 2\n```\n\nA primeira linha da saída,\n\n``` text\nThe decimal point is 1 digit(s) to the right of the |\n```\n\ninforma a posição da casa decimal e deve ser observada antes da interpretação do diagrama.\n\n**O que aconteceu com `scale = 1`?**\n\nObserve que os ramos apresentados pelo R são\n\n$$0,\\quad 2,\\quad 4,\\quad 6,\\quad 8,\\quad 10.$$\n\nIsso é diferente da construção manual anterior, na qual utilizamos um ramo para cada dezena.\n\nPara este conjunto de dados, com `scale = 1`, o R produziu uma representação mais **compacta**: os ramos ímpares são incorporados às linhas dos ramos pares imediatamente anteriores.\n\nAssim, podemos interpretar a organização das linhas aproximadamente como:\n\n| Ramo exibido | Valores reunidos  |\n|-------------:|:------------------|\n|          `0` | 0 a 19 minutos    |\n|          `2` | 20 a 39 minutos   |\n|          `4` | 40 a 59 minutos   |\n|          `6` | 60 a 79 minutos   |\n|          `8` | 80 a 99 minutos   |\n|         `10` | 100 a 119 minutos |\n\nPortanto, o ramo `0` **não significa que existam tempos de deslocamento próximos de zero**. Nesta representação, a mesma linha também incorpora os valores da faixa dos 10 minutos.\n\nPor isso, a primeira linha\n\n``` text\n0 | 23344555788\n```\n\ncontém os menores tempos observados, que, após a aproximação utilizada pela função, correspondem a valores próximos de\n\n$$12,\\ 13,\\ 13,\\ 14,\\ 14,\\ 15,\\ 15,\\ 15,\\ 17,\\ 18,\\ 18.$$\n\n::: {.callout-warning title=\"Não leia apenas ramo + folha\"}\nNa construção manual que fizemos anteriormente,\n\n``` text\n1 | 2\n```\n\nsignificava diretamente 12 minutos.\n\nNa saída automática do `stem()`, essa regra só pode ser utilizada depois de compreendermos a **escala adotada pelo R**.\n\nQuando `scale = 1` produz uma representação compactada, uma mesma linha pode incorporar duas dezenas consecutivas. Por isso, a informação fornecida pelo programa sobre a posição decimal e a estrutura dos ramos deve ser examinada antes da leitura das folhas.\n:::\n\nEsse comportamento também pode ser percebido na linha iniciada pelo ramo `2`, que reúne valores dos 20 e dos 30 minutos.\n\nA compactação tem uma vantagem: os 80 valores podem ser apresentados em poucas linhas. A desvantagem é que a leitura deixa de ser tão imediata quanto no diagrama construído manualmente.\n\n**Alterando `scale`**\n\nPodemos solicitar ao R uma representação mais detalhada aumentando `scale`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem(\n  dados$tempo_deslocamento_min,\n  scale = 2\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n   1 | 23344555788\n   2 | 00222244556678888\n   3 | 0011222344466888999\n   4 | 11556777\n   5 | 01122233778\n   6 | 1377999\n   7 | 368\n   8 | 6\n   9 | 79\n  10 | \n  11 | 2\n```\n\n\n:::\n:::\n\n\n\n\nO argumento `scale` **não modifica os dados**. Ele modifica somente o grau de detalhamento vertical do diagrama.\n\nCom\n\n``` r\nscale = 2\n```\n\no R procura produzir uma representação aproximadamente duas vezes mais longa que a obtida com `scale = 1`.\n\nIsso geralmente reduz a quantidade de observações reunidas em uma mesma linha e facilita a identificação da estrutura da distribuição.\n\n::: {.callout-tip title=\"Como escolher `scale`?\"}\nNão existe um único valor de `scale` que seja necessariamente o melhor para todos os conjuntos de dados.\n\nUma estratégia prática é:\n\n1.  começar com `scale = 1`;\n2.  observar se existem muitas folhas concentradas em poucas linhas;\n3.  aumentar para `scale = 2` quando a representação estiver excessivamente compacta;\n4.  experimentar valores maiores se ainda for necessário aumentar o detalhamento.\n\nA escolha deve favorecer a **leitura da distribuição**, sem produzir um diagrama excessivamente longo ou fragmentado.\n\nPara fins didáticos, é interessante comparar pelo menos\n\n``` r\nstem(\n  dados$tempo_deslocamento_min,\n  scale = 1\n)\n```\n\ncom\n\n``` r\nstem(\n  dados$tempo_deslocamento_min,\n  scale = 2\n)\n```\n\ne observar como os mesmos dados são distribuídos entre um número diferente de linhas.\n:::\n\n::: {.callout-note title=\"Atenção à precisão dos dados\"}\nA variável `tempo_deslocamento_min` possui valores com casas decimais.\n\nPara construir o diagrama, `stem()` utiliza uma precisão compatível com a escala escolhida e pode não exibir todos os algarismos presentes nos dados originais.\n\nAssim, o diagrama de ramo e folhas preserva mais informação individual que uma distribuição agrupada em classes, mas não significa necessariamente que todas as casas decimais originais serão reproduzidas.\n:::\n\nAo analisar o diagrama, devemos observar onde se encontra a maior concentração de folhas, como elas se distribuem ao longo dos ramos, se existem regiões sem observações e se alguns valores aparecem muito afastados da região de maior concentração.\n\nO diagrama de ramo e folhas permite, portanto, observar a **forma da distribuição** e, simultaneamente, manter uma ligação mais próxima com os valores individuais. :::\n\nO pacote `fmsb` também produz o diagrama de ramos e folhas e insere em um ambiente gráfico:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fmsb)\nfmsb::gstem(\n  dados$tempo_deslocamento_min\n)\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-70-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Curva de densidade\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_density() +\n  labs(\n    title = \"Curva de densidade do tempo de deslocamento\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Densidade\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n\n\nHistograma e densidade podem ser comparados na mesma escala:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    binwidth = 15,\n    boundary = 10,\n    closed = \"left\"\n  ) +\n  geom_density() +\n  labs(\n    title = \"Histograma e curva de densidade\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Densidade\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-72-1.png){width=672}\n:::\n:::\n\n\n\n\nCompare diferentes larguras de banda:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_density(adjust = 0.5) +\n  labs(\n    title = \"Menos suavização\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Densidade\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-73-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  ggplot(\n    aes(x = tempo_deslocamento_min)\n  ) +\n  geom_density(adjust = 2) +\n  labs(\n    title = \"Mais suavização\",\n    x = \"Tempo de deslocamento (min)\",\n    y = \"Densidade\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-distribuicoes-frequencias-representacoes-graficas-v2_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n:::\n\n\n\n\nA forma da densidade não é independente da escolha de suavização. Assim como no histograma, vale a pena verificar se a interpretação geral é robusta a escolhas razoáveis.\n\n## Escolhendo uma representação adequada\n\nUma representação estatística deve ser escolhida em função da **natureza da variável** e do **objetivo da análise**.\n\n| Tipo de variável | Tabela/organização | Representações frequentes |\n|:-----------------------|:-----------------------|:-----------------------|\n| Qualitativa nominal | categorias e frequências | barras, Pareto, setores |\n| Qualitativa ordinal | categorias em ordem natural e frequências | barras ordenadas |\n| Quantitativa discreta | valores distintos e frequências | barras, pontos |\n| Quantitativa contínua | valores individuais ou classes | histograma, polígono, ogiva, ramo e folhas, densidade |\n\nEsse quadro é uma orientação inicial, não uma regra absoluta.\n\nAo interpretar um gráfico, pergunte:\n\n1.  qual variável está sendo representada?\n2.  qual é sua unidade de medida?\n3.  o que aparece em cada eixo?\n4.  as frequências são absolutas, relativas, percentuais ou acumuladas?\n5.  onde os dados estão mais concentrados?\n6.  existem regiões pouco ocupadas ou lacunas?\n7.  há observações que merecem investigação?\n8.  a escolha gráfica facilita ou dificulta a leitura?\n\n::: {.callout-tip title=\"Construir é apenas parte da análise\"}\nO objetivo não é produzir gráficos por produzir. Uma representação gráfica deve ajudar a formular ou responder perguntas sobre os dados.\n:::\n\n### Erros comuns em tabelas e gráficos\n\nEvite:\n\n- utilizar frequência acumulada para categorias sem ordem;\n- esconder qual denominador foi utilizado nos percentuais;\n- ordenar uma variável ordinal pela frequência e destruir sua ordem natural;\n- utilizar códigos de categoria sem explicar seus significados;\n- confundir gráfico de barras com histograma;\n- utilizar classes que não cobrem todos os valores ou que se sobrepõem;\n- escolher número de classes mecanicamente sem observar o efeito no histograma;\n- omitir títulos, unidades ou rótulos essenciais;\n- utilizar efeitos tridimensionais que não acrescentam informação;\n- interpretar uma curva de densidade como se o eixo vertical fosse uma contagem;\n- apresentar muitas casas decimais sem necessidade;\n- repetir em texto todos os valores já visíveis na tabela.\n\n## Exercícios de consolidação\n\n### Exercícios conceituais\n\n#### Exercício 1 — Número de livros lidos\n\nO número de livros lidos por 24 estudantes no último semestre foi:\n\n$$0,\\ 1,\\ 2,\\ 1,\\ 3,\\ 2,\\ 0,\\ 4,\\ 1,\\ 2,\\ 2,\\ 3,$$\n\n$$1,\\ 0,\\ 2,\\ 5,\\ 1,\\ 3,\\ 2,\\ 1,\\ 4,\\ 2,\\ 0,\\ 3.$$\n\n1.  Classifique a variável.\n2.  Construa o rol.\n3.  Construa a distribuição de frequências absoluta, relativa e percentual.\n4.  Acrescente frequências acumuladas.\n5.  Qual percentual leu exatamente dois livros?\n6.  Qual percentual leu no máximo dois livros?\n7.  Qual percentual leu pelo menos três livros?\n8.  Qual representação gráfica você escolheria? Justifique.\n\n#### Exercício 2 — Variável nominal\n\nUma pesquisa registrou o tipo de conexão à internet utilizado por 50 estudantes:\n\n| Conexão      | Frequência |\n|:-------------|-----------:|\n| Fibra        |         28 |\n| Dados móveis |         11 |\n| Cabo         |          7 |\n| Rádio        |          3 |\n| Outra        |          1 |\n\n1.  Calcule frequências relativas e percentuais.\n2.  Frequências acumuladas possuem interpretação natural? Explique.\n3.  Construa a ordenação necessária para um gráfico de Pareto.\n4.  Qual gráfico seria mais eficiente para comparar as categorias: barras ou setores? Justifique.\n\n#### Exercício 3 — Variável ordinal e valores ausentes\n\nUma pesquisa obteve 100 participantes. Para a variável `satisfação`, oito pessoas não responderam. Entre as 92 respostas válidas:\n\n- 15 foram `Baixa`;\n- 27 foram `Média`;\n- 50 foram `Alta`.\n\nCalcule:\n\n1.  os percentuais entre as 92 respostas válidas;\n2.  os percentuais entre os 100 participantes;\n3.  o percentual de ausência;\n4.  explique por que os dois denominadores respondem a perguntas diferentes;\n5.  construa as frequências acumuladas entre as respostas válidas.\n\n#### Exercício 4 — Construção de uma tabela por classes\n\nConsidere uma variável quantitativa contínua com:\n\n$$n=60,\\qquad x_{\\min}=12{,}4,\\qquad x_{\\max}=48{,}9.$$\n\n1.  Calcule a amplitude total.\n2.  Obtenha um número inicial de classes pela regra da raiz quadrada.\n3.  Obtenha o número sugerido por Sturges.\n4.  Escolha uma proposta de $k$ e calcule uma largura inicial $h=A/k$.\n5.  Ajuste os limites para valores de leitura conveniente.\n6.  Explique quais critérios deve verificar para garantir que as classes formem uma partição adequada.\n\n#### Exercício 5 — Identificando erros\n\nUm relatório apresenta as classes:\n\n$$[0;10],\\quad[10;20],\\quad[20;30].$$\n\n1.  Explique por que essa notação pode gerar ambiguidade para os valores `10` e `20`.\n2.  Reescreva as classes utilizando uma convenção sem sobreposição.\n3.  Por que lacunas entre classes também seriam problemáticas?\n\n#### Exercício 6 — Leitura da tabela contínua\n\nUtilize a tabela de tempo de deslocamento deste capítulo.\n\n1.  Quantos estudantes levam entre 40 e menos de 55 minutos?\n2.  Qual percentual leva menos de 55 minutos?\n3.  Quantos levam pelo menos 70 minutos?\n4.  Qual é a classe modal?\n5.  Qual ponto médio representa a classe $[55;70)$?\n6.  Explique a diferença entre $f_i$ e $F_i$ para a classe $[40;55)$.\n\n#### Exercício 7 — Escolha crítica do gráfico\n\nPara cada situação, indique uma representação adequada e justifique:\n\n1.  curso de graduação;\n2.  nível de satisfação em cinco categorias ordenadas;\n3.  número de irmãos;\n4.  altura de 200 estudantes;\n5.  distribuição acumulada do tempo de deslocamento;\n6.  conjunto de 25 valores quantitativos quando se deseja preservar os valores individuais.\n\n### Exercícios no R\n\n#### Exercício 8 — Tabela e barras\n\nUtilize `curso` no banco do capítulo.\n\n1.  construa a tabela de frequências;\n2.  calcule percentuais;\n3.  produza gráfico de barras;\n4.  ordene as barras por frequência;\n5.  escreva duas frases interpretativas.\n\n#### Exercício 9 — Ordinal\n\nUtilize `satisfacao`.\n\n1.  confirme os níveis do fator;\n2.  construa $f_i$, $f_{r_i}$, percentual, $F_i$ e $F_{r_i}$;\n3.  construa gráfico de barras preservando a ordem;\n4.  explique por que ordenar pela frequência seria inadequado.\n\n#### Exercício 10 — Quantitativa discreta\n\nUtilize `faltas`.\n\n1.  construa a tabela completa;\n2.  determine quantos estudantes tiveram exatamente duas faltas;\n3.  determine quantos tiveram no máximo duas;\n4.  determine quantos tiveram pelo menos três;\n5.  construa um gráfico de barras e um gráfico de pontos;\n6.  compare a informação visual oferecida pelos dois.\n\n#### Exercício 11 — Regras de classes\n\nUtilize `altura_m`.\n\n1.  calcule $n$, mínimo, máximo e amplitude;\n2.  obtenha as sugestões de Sturges, Scott e Freedman--Diaconis;\n3.  compare os resultados;\n4.  escolha uma configuração e justifique-a.\n\n#### Exercício 12 — Tabela contínua completa\n\nUtilize `altura_m`.\n\n1.  defina limites adequados;\n2.  utilize `cut()` para criar as classes;\n3.  construa a tabela com ponto médio, $f_i$, $f_{r_i}$, percentual, $F_i$ e $F_{r_i}$;\n4.  faça todas as verificações de consistência;\n5.  produza um histograma com os mesmos limites da tabela.\n\n#### Exercício 13 — Ogiva e densidade\n\nUtilize `tempo_deslocamento_min`.\n\n1.  construa uma ogiva em percentual acumulado;\n2.  construa a função de distribuição empírica;\n3.  explique a principal diferença entre as duas;\n4.  construa uma curva de densidade;\n5.  compare `adjust = 0.5`, `adjust = 1` e `adjust = 2`.\n\n#### Exercício 14 — Mini-relatório exploratório\n\nEscolha uma variável do banco e produza, em Quarto, uma análise contendo:\n\n1.  identificação e classificação da variável;\n2.  número de observações válidas;\n3.  tabela de frequências adequada;\n4.  representação gráfica coerente;\n5.  pelo menos três frases de interpretação;\n6.  uma observação sobre alguma decisão tomada durante a análise.\n\n::: {.callout-important title=\"Síntese do capítulo\"}\nUma distribuição de frequências transforma observações individuais em uma visão estruturada da variável. Para categorias e valores discretos, a tabela apresenta diretamente cada valor e sua frequência. Para dados contínuos, muitas vezes é necessário agrupar observações em classes.\n\nAs representações gráficas devem surgir como extensão dessa organização: barras comparam categorias ou valores discretos; histogramas representam intervalos contínuos; polígonos utilizam pontos médios; ogivas utilizam frequências acumuladas; ramo e folhas preserva valores individuais; curvas de densidade oferecem uma visão suavizada da distribuição.\n\nO R automatiza esses procedimentos, mas não substitui as decisões estatísticas sobre classificação da variável, denominadores, ordem, classes, representação e interpretação.\n:::\n\n## Referências de apoio {.unnumbered}\n\nBUSSAB, Wilton de Oliveira; MORETTIN, Pedro Alberto. *Estatística básica*. 8. ed. São Paulo: Saraiva, 2013.\n\nCLEVELAND, William S. *The elements of graphing data*. Monterey: Wadsworth, 1985.\n\nDALGAARD, Peter. *Introductory statistics with R*. 2. ed. New York: Springer, 2008.\n\nFREEDMAN, David; DIACONIS, Persi. On the histogram as a density estimator: $L_2$ theory. *Zeitschrift für Wahrscheinlichkeitstheorie und Verwandte Gebiete*, v. 57, p. 453--476, 1981.\n\nHOAGLIN, David C.; MOSTELLER, Frederick; TUKEY, John W. *Understanding robust and exploratory data analysis*. New York: John Wiley & Sons, 1983.\n\nSCOTT, David W. On optimal and data-based histograms. *Biometrika*, v. 66, n. 3, p. 605--610, 1979.\n\nSTURGES, Herbert A. The choice of a class interval. *Journal of the American Statistical Association*, v. 21, n. 153, p. 65--66, 1926.\n\nTUKEY, John W. *Exploratory Data Analysis*. Reading, Massachusetts: Addison-Wesley, 1977.\n\nWICKHAM, Hadley. *ggplot2: Elegant Graphics for Data Analysis*. 2. ed. Cham: Springer, 2016.\n\nWITTE, Robert S.; WITTE, John S. *Statistics*. Hoboken: Wiley, 2013.\n",
    "supporting": [
      "04-distribuicoes-frequencias-representacoes-graficas-v2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}